### ISSUE TITLE
Themes doesn't show up and im on latop

### ISSUE THREAD

**Issue by FlisksRevenge** [BetterDiscord/Installer#100]
**Describe the bug**

**To Reproduce**
1. I downloaded betterdiscord
2. I clicked windows
3. I downloaded a theme 
4. I clicked user settings

**Expected behavior**
    and theme's didn't show up

**Screenshots**

**System Information:**
 - Latop 
- Discord Version: [eg. Stable]

**Additional context**

**Comment by FlackoLOL** [comment]
Me too

**Comment by rauenzi** [comment]
This doesn't really give much information. Please include the installer log and client versions.

**Comment by FlisksRevenge** [comment]
I downloaded the latest version but it didnt work for some reason i
dont know why it didnt work but that is stupid i tried on a computer a
laptop and nothing worked so that is dumb please make a better version that
works on laptop!!! cause i really want to see custom backgrounds btw i can
see the folder but i cant see the tab in discord i opened the app and the
discord chrome on google and nothing worked so please fix this immediately
i dont want to be the only one left out :(

>
