### ISSUE TITLE
Another BetterDiscord Not Starting Correctly Bug

### ISSUE THREAD

**Issue by DarcPhansea** [BetterDiscord/Installer#101]
**Describe the bug**
Better Discord Wont Finish Loading (Has to go with guild loading)

**To Reproduce**
1. Have all guilds in folders
2. Close all guild folders
3. Restart discord

**Expected behavior**
BetterDiscord to start properly

**System Information:**
 - OS: [Manjaro]
- Discord Version: [Stable]

**To Fix For Coders**
Probably add some detection to guilds inside of folders for the '[BetterDiscord] [Startup] Waiting for guilds.' check

**To Fix For Users**
Just open any server folders you have closed. Or you leave at least 1 guild not in a folder. And it should finish loading.

**Comment by rauenzi** [comment]
Please reinstall, there was a fix pushed out for this.
