### ISSUE TITLE
better Discord not working

### ISSUE THREAD

**Issue by NickThe4th** [BetterDiscord/Installer#102]
Hello,

i tired to start Better Discord, but it wont work.
Better Discord is not starting with Discord and there is no upper bar with x-Icon.

i tried to reinstall or to repair it, thta doesnt work either.

![Discord](https://user-images.githubusercontent.com/82637869/114982548-e423de80-9e8f-11eb-83fb-6a6fcee1f77a.png)

Im using Discord on Windows and on Stable

Lg
Raz

**Comment by garridinsi** [comment]
If you have updated Discord, close discord completely by task manager and repair it by the new installer

**Comment by NickThe4th** [comment]
That fixed it, thanks
