### ISSUE TITLE
Fatal Javascript error

### ISSUE THREAD

**Issue by Yoda280** [BetterDiscord/Installer#104]
https://user-images.githubusercontent.com/73242022/115063304-01b57000-9eb1-11eb-8289-9665e72a4665.png
i open installer and press repair betterdiscord i get this error every time

**Comment by rauenzi** [comment]
Go delete this directory `%appdata%\discord\0.0.309` then restart Discord. Then reinstall BD.

**Comment by RIPzValidTV** [comment]
![image (89)](https://user-images.githubusercontent.com/82731323/115126036-e6438580-9fd4-11eb-8188-ee512d7cd84b.jpeg)
I open the installer, either I install or repair, the same outcome. Any help? I deleted the 0.0.306 directory since I didn't have 9.0.309 and no difference.

**Comment by Arias122** [comment]
I dunno i even don’t know What website isn’t fake and where can i install better discord.?Maybe somewone help me?

Maja Julko
