### ISSUE TITLE
Client freezes when right-clicking on server

### ISSUE THREAD

**Issue by asorel1942** [BetterDiscord/Installer#105]
**Describe the bug**
When right clicking on a server in the server menu, client will freeze and remain frozen until Discord is restarted. Have already attempted:
- repairing installation
- deleting version folder in .config/discord, then uninstalling and reinstalling BetterDiscord

**System Information:**
 - Manjaro KDE 5.11
- Stable
![image](https://user-images.githubusercontent.com/33983895/115101833-45da5c00-9f15-11eb-827e-0ef52b172741.png)

**Comment by guihkx** [comment]
Which Discord AUR package are you using?

**Comment by asorel1942** [comment]
I'm using the Discord client from the Official Repositories (community). However, I'm no longer seeing the issue after a restart (despite that not fixing the issue before), so there's not much more for me to diagnose.
