### ISSUE TITLE
Plugin updater on Mac downloads to the old directory

### ISSUE THREAD

**Issue by asportnoy** [BetterDiscord/Installer#107]
**Describe the bug**
After updating to the new installer, the plugin folder location changed from `~/Library/Preferences/BetterDiscord` to `~/Library/Application Support/betterdiscord`. When I use the plugin update popups, the updates install on the old directory
 
**To Reproduce**
1. Install a plugin that needs updating
2. Click on the update button in the banner
3. Reload Discord and it'll say they still need updating
4. Look in the old folder and the updated version plugin will be there

**Expected behavior**
The updater installs to the correct plugin folder

**Screenshots**
Trying to use the updater:
https://user-images.githubusercontent.com/14863373/115150564-8b3e7c80-a02e-11eb-8f16-cc554ea2eb40.mp4
Old plugin folder:
![image](https://user-images.githubusercontent.com/14863373/115150613-c6d94680-a02e-11eb-93ff-12a01970c137.png)

**System Information:**
 - OS: macOS
- Discord Version: Canary
- BD 1.0.0 (stable)

**Additional context**
I'm using the new BD installer

**Comment by Tropix126** [comment]
This is neither related to the installer nor BD. BD itself has no built-in plugin updater at the moment, so this is likely a problem with a library (BDFDB and ZLib come to mind).

**Comment by asportnoy** [comment]
Ah, thought the updater was built in. I'll check the others, thanks.
