### ISSUE TITLE
App-0.0.305 instead of app-0.0.309

### ISSUE THREAD

**Issue by ASimpleIt** [BetterDiscord/Installer#108]
![image](https://user-images.githubusercontent.com/82797688/115190726-30d00b00-a084-11eb-83a4-ca79953a299e.png)
App-0.0.305 may be killing BetterDiscord
Starting Repair...

Creating required directories...
✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\UserName\AppData\Local\Discord\app-0.0.305\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord not running
✅ Discord restarted

Repair completed!
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord
✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\data
✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\themes
✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\UserName\AppData\Local\Discord\app-0.0.305\resources
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord
✅ Discord restarted

Install completed!

Run BetterDiscord Installer v1.0.0-beta Latest Release
Locate Discord in Local,
Find folder app-0.0.305 instead of app-0.0.309

**Expected behavior**
Discord With working themes

![image](https://user-images.githubusercontent.com/82797688/115189705-9de2a100-a082-11eb-9642-7ba3f2c2cbef.png)

**System Information:**
OS: Windows
Discord: Stable 82590 (bf3e4f7)
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

Already tried running the installer after deleting both Roaming/BetterDiscord and app-0.0.305

**Comment by ASimpleIt** [comment]
![image](https://user-images.githubusercontent.com/82797688/115191865-bacca380-a085-11eb-9a8f-3e3d15327936.png)
Oh no, there is two of them now

**Comment by dav1312** [comment]
If your host is `1.0.9001` you need to install BD in `app-1.0.9001`.
If you don't have it, reinstalling Discord may be your best bet

**Comment by rauenzi** [comment]
Please see the above, you're running an outdated (and seemingly broken) version of Discord

**Comment by Bart-Developer** [comment]
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\ClinicaItalia01\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\ClinicaItalia01\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\ClinicaItalia01\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\ClinicaItalia01\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by eceleman1231** [comment]
> ![image](https://user-images.githubusercontent.com/82797688/115190726-30d00b00-a084-11eb-83a4-ca79953a299e.png) App-0.0.305 may be killing BetterDiscord Starting Repair...
> 
> Creating required directories... ✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord ✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\data ✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\themes ✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord\plugins ✅ Directories created
> 
> Downloading asar file ✅ Package downloaded
> 
> Injecting shims... Injecting into: C:\Users\UserName\AppData\Local\Discord\app-0.0.305\resources ✅ Injection successful ✅ Shims injected
> 
> Restarting Discord... Attempting to kill Discord ✅ Discord not running ✅ Discord restarted
> 
> Repair completed! Starting Install...
> 
> Creating required directories... ✅ Directory exists: C:\Users\UserName\AppData\Roaming\BetterDiscord ✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\data ✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\themes ✅ Directory created: C:\Users\UserName\AppData\Roaming\BetterDiscord\plugins ✅ Directories created
> 
> Downloading asar file ✅ Package downloaded
> 
> Injecting shims... Injecting into: C:\Users\UserName\AppData\Local\Discord\app-0.0.305\resources ✅ Injection successful ✅ Shims injected
> 
> Restarting Discord... Attempting to kill Discord ✅ Discord restarted
> 
> Install completed!
> 
> Steps to reproduce the behavior: Run BetterDiscord Installer v1.0.0-beta Latest Release Locate Discord in Local, Find folder app-0.0.305 instead of app-0.0.309
> 
> **Expected behavior** Discord With working themes
> 
> ![image](https://user-images.githubusercontent.com/82797688/115189705-9de2a100-a082-11eb-9642-7ba3f2c2cbef.png)
> 
> **System Information:** OS: Windows Discord: Stable 82590 (bf3e4f7) Host 1.0.9001 Windows 10 64-Bit (10.0.19042)
> 
> Already tried running the installer after deleting both Roaming/BetterDiscord and app-0.0.305
