### ISSUE TITLE
Can't install, repair or uninstall

### ISSUE THREAD

**Issue by Stillahumanso** [BetterDiscord/Installer#109]
Can't install, repair or uninstall

**Comment by dav1312** [comment]
That provides no useful information at all

**Comment by Tropix126** [comment]
@dav1312 is correct that your issue does not provide enough information to help. Please reopen this issue using the proper bug report template.

**Comment by dav1312** [comment]
> @dav1312 is correct that your issue does not provide enough information to help. Please reopen this issue using the proper bug report template.

It was not my issue tho🤣
