### ISSUE TITLE
Discord crashing when installing Better Discord

### ISSUE THREAD

**Issue by TheAlrightGuy** [BetterDiscord/Installer#110]
So my computer just updated and lost my better discord, tried reinstalling BD and it crashes my discord. So I decided to uninstall my discord and reinstall it and tried again still the same issue. I get this message while using the installer "BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord."

Please help I really enjoy/need what BD offers.

**Comment by howoshi** [comment]
All you need to do is open the installer for betterdiscord and click the repair option. It will ask if you'd like it to redownload after the repair, click yes. You should be good to go after!

**Comment by Max-Power-7** [comment]
I did the same steps that @howoshi  describes and nothing, I still have the same problem described by @TheAlrightGuy but in the Discord Canary and PTB clients ...
Until an hour ago they were going well for me, I don't know what happened, it was closed and this message appeared repeatedly:

![image](https://user-images.githubusercontent.com/53453234/115814405-f7b8d300-a3c2-11eb-8215-c5e7751bdb86.png)

**Comment by QuintenVanDerBlom** [comment]
I've got exactly the same issue when installing BD. I have tried what @howoshi described, but it still does not work. I do however see a blue pop up just before the crash that has something to do with the emotes. I hope there is a solution for this soon.

**Comment by zerebos** [comment]
As an extreme option go and rename the existing BD folder (`%appdata%\BetterDiscord` on Windows) to something else as a backup then reinstall BD.

**Comment by preaksoon42** [comment]
Hello my friend,

%appdata%\BetterDiscord Go here and delete the contents of the folder, then install betterdiscord again. The problem will be resolved.

**Comment by shahrul11111** [comment]
Hi! If you're experiencing the same problem as Max-Power-7, I highly recommend that you follow the steps that rauenzi and preaksoon42 has provided as it helped me to get rid of this problem in less than 5 minutes! Thank you rauenzi and preaksoon42!

**Comment by chuigobrrrr** [comment]
I am on mac do you guy have the fix that preaksoon42 said but on mac?

**Comment by HPCbro** [comment]
%appdata%\BetterDiscord\plugin clear file
если это помогло значит какой-то плагин устарел

**Comment by hyperlite1** [comment]
Hi, and i just need the fix to this on mac
