### ISSUE TITLE
Proxy Problem.

### ISSUE THREAD

**Issue by Snapdays** [BetterDiscord/Installer#112]
**Describe the bug**
Probably an proxy issue while trying to install BTD

Please maybe provide turning off VPN while downloading, will remove allot of questions from the discord.

**Comment by Tropix126** [comment]
Forcefully disabling VPNs without the users knowledge would be a breach of privacy on their end as well as a possible red flag for antiviruses to catch. Hoping once our new website is out that we can provide better troubleshooting documentation to users.
