### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by Smugchild** [BetterDiscord/Installer#113]
Better discord, when installed does not open, neither does the actual discord application. Nothing pops up but it also shows no background processes which is really strange?

**Comment by Max-Power-7** [comment]
It is happening to me right now with DiscordPTB and DiscordCanary, just BD breaks with the discord clients, it is strange because until an hour ago they were doing quite well for me.

![image](https://user-images.githubusercontent.com/53453234/115814059-59c50880-a3c2-11eb-8e7a-4367d6086b5b.png)

**Comment by ChifuyuNee** [comment]
Got the same problem, but only when i'm connecting into a VC or looking for a GIF makes BD crash

**Comment by dav1312** [comment]
> Got the same problem, but only when i'm connecting into a VC or looking for a GIF makes BD crash

There are GIFs that are made to crash your Discord. That is not a BD problem. They crash people with BD and without it.
If you are a moderator on the server those GIFs are sent, I recommend you ban that person

**Comment by ChifuyuNee** [comment]
> > Got the same problem, but only when i'm connecting into a VC or looking for a GIF makes BD crash
> 
> There are GIFs that are made to crash your Discord. That is not a BD problem. They crash people with BD and without it.
> If you are a moderator on the server those GIFs are sent, I recommend you ban that person

It's litterally every GIF, ik about gifs.
but yea got same problem since yesterday everytime i'm in a VC, streaming, w./(or not) cam

**Comment by mkcoldwolf** [comment]
Can reproduce, Whenever u join a VC that someone streaming, BD does crush without any plugin enabled

**Comment by DexLuther** [comment]
I'm in the same boat. BD crashes when joining a VC call in a server (no streaming was happening). Discord crashed, PTB would restart and a message pops up as in the screenshot someone else posted that BS was temporality disabled due to the crash. Then PTB would close entirely.

Attempting to open PTB again would put me back into the VC, which would crash BD again, which would crash the whole client.

Normal Discord does not seem to be affected (yet).

**Comment by mkcoldwolf** [comment]
> I'm in the same boat. BD crashes when joining a VC call in a server (no streaming was happening). Discord crashed, PTB would restart and a message pops up as in the screenshot someone else posted that BS was temporality disabled due to the crash. Then PTB would close entirely.
> 
> Attempting to open PTB again would put me back into the VC, which would crash BD again, which would crash the whole client.
> 
> Normal Discord does not seem to be affected (yet).
> 
> EDIT: Repairing and then reinstalling BD on PTB seems to have fixed the issue **at least temporarily**. If you're having the issue try downloading the latest BD from here: https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta (download a new copy even if you have it already)

I already tried to reinstall latest BD it got no luck for me (i didn't delete the BD folder a full reinstall)
I'll try that when i got time

**Comment by Tropix126** [comment]
The comments of this issue and the actual issue opened are three completely different issues.
For the installer not opening, try this alternate 7-zip self-extracting archive build => https://cdn.discordapp.com/attachments/603225817262194699/832679035644805190/BetterDiscord-Windows.exe
For crashing issues, these should be directed to https://github.com/rauenzi/betterdiscordapp
