### ISSUE TITLE
Crashing on latest Discord PTB version when joining a call

### ISSUE THREAD

**Issue by TonyGamer** [BetterDiscord/Installer#114]
**Describe the bug**
On the latest version of Discord PTB, betterdiscord causes a crash when joining a call in a server I'm not sure what the exact conditions are to reproduce, but the behavior results in a "betterdiscord has crashed your client" message, yet continues to crash in a loop afterwards. Uninstalling betterdiscord did not help, I had to completely reinstall Discord PTB to fix the issue.

**To Reproduce**
1. Go to any server
2. Enter a voice channel
3. Crash
4. Auto Discord Restart
5. Go back to Step 3

**Expected behavior**
Discord does not crash and instead joins the call with no issue

**System Information:**
 - OS: Arch Linux (5.11.15-arch1-2)
- Discord Version: Discord PTB

**Comment by ChifuyuNee** [comment]
Same Problem of #113

**Comment by alaley40** [comment]
I got a bug

**Comment by zerebos** [comment]
This bug should be directed to the client https://github.com/rauenzi/BetterDiscordApp
