### ISSUE TITLE
"Public" servers button that asks a developer app to access my account name

### ISSUE THREAD

**Issue by CEOofGit** [BetterDiscord/Installer#117]
How do I get rid of this button? I don't want/need it.
![image](https://user-images.githubusercontent.com/64725743/116349986-47751f80-a845-11eb-93fe-3f0e1f632edc.png)

**Comment by dav1312** [comment]
1) This is not an issue with the installer
2) Since this is something that BD adds, have you even tried checking the BD settings?!?!?!?! 😑
