### ISSUE TITLE
Discord Overlay Blinking

### ISSUE THREAD

**Issue by gb85150** [BetterDiscord/Installer#118]
**Describe the bug**
Discord In-game Overlay Blinking bug

**To Reproduce**
1. Toggle in game overlay
2. Open your game
3. Press your keybind for opening the in-game overlay

**Expected behavior**
Stop the blinking of overlay

**System Information:**
- OS: Windows 10 Pro 20H2 (19042.928)
- Discord Version: Stable 83223 (6de9715)
- BD Version: 1.0.0 (stable)

**Additional context**
I already tried with disabling my custom themes : won't fix

**Comment by Tropix126** [comment]
This is an issue with the client, not the installer and should be directed to https://github.com/rauenzi/betterdiscordapp.
