### ISSUE TITLE
BetterDiscord crashing after updates

### ISSUE THREAD

**Issue by monckey100** [BetterDiscord/Installer#120]
**Describe the bug**
See screenshot:
![image](https://user-images.githubusercontent.com/5633486/116448218-b46cc300-a80d-11eb-9f03-4448d7ed481c.png)

**To Reproduce**
- I found out that McAfee is actually deleting some files BetterDiscord installs under the guise of protection.
- Try to launch application after mcAfee has quarantined "Index.js"

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: Windows 10
- Discord Version: Stable

**Additional context**

**Comment by Haxorzz** [comment]
I think the real problem is that you're using McAfee in 2021

**Comment by zerebos** [comment]
This bug should be directed to the client https://github.com/rauenzi/BetterDiscordApp
