### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by Curstantine** [BetterDiscord/Installer#127]
Installation process goes as it should be, but "discord restarted" or "discord killed" doesn't actually do anything.  
Tried both Canary and Stable same result.

**To Reproduce**
Normal installation from the appimage located on both the website and here in github releases.

**Expected behavior**
Themes, Plugins and Settings to show up in the left bar when user settings is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/69104500/118255934-7e486800-b4ca-11eb-9674-9aba285f5c15.png)  
![image](https://user-images.githubusercontent.com/69104500/118256024-9ddf9080-b4ca-11eb-8e13-e5a5d230c9e5.png)
![image](https://user-images.githubusercontent.com/69104500/118257662-81dcee80-b4cc-11eb-903c-da2d0cbcab48.png)

**System Information:**
- OS: Manjaro 21.0.4 Ornara.  
- Discord Version: Stable 84785 (fe5e237)  
- SHA-1? : ef627297fcbb6330143efa82f8029a53fb65de2e

**Comment by ObserverOfTime** [comment]
If you're still having this issue, you can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl) instead.

**Comment by Curstantine** [comment]
> If you're still having this issue, you can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl) instead.

Ah hello it's been awhile!
Yeah I tried, it gave me that known problem.  
The one where discord becomes a "web" client thing for some reason.

**Comment by Curstantine** [comment]
Alright so it didn't work with the [Arch package](https://archlinux.org/packages/community/x86_64/discord/).  
So I downloaded the package from discord and it works now for some reason.
