### ISSUE TITLE
BetterDiscord not showing up in settings

### ISSUE THREAD

**Issue by 7X-Z0** [BetterDiscord/Installer#132]
I've had BetterDiscord for a while and then it stopped showing up the themes and plugins in settings out of nowhere. I've tried using the fix, I've tried removing the plugins, I've tried completely reinstalling it, but none of it works. It shows that Better Discord is installed but not plugins and themes don't show up in settings.
![Capture](https://user-images.githubusercontent.com/64157660/119213851-41630f00-ba90-11eb-836e-0af4a305c5c8.PNG)

**Comment by Shadow-386** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/84611075/119214952-608f8a00-baec-11eb-8611-fadc9264fb95.png)
Exactly, same here. Once BetterDiscord attempts to load emotes. It shows the message
"BetterDiscord failed to load emotes. Please check your internet connection and firewall." I checked and did the everything just like 7Z-Z0 but no avail.

**Comment by zackbriccs** [comment]
I also have the same problem but the theme I have is still activated. I tried repairing, reinstalling, relaunching and stuff and it doesn't work.

**Comment by Shadow-386** [comment]
> I also have the same problem but the theme I have is still activated. I tried repairing, reinstalling, relaunching and stuff and it doesn't work.

It happened like today. So if you already had your theme activated it'd be there. It's probably a bug in the newer version

**Comment by Veysinator** [comment]
![resim](https://user-images.githubusercontent.com/71281955/119221858-12818300-bafa-11eb-9ae4-1a84dea525c6.png)
Updated to Discord Canary 1.0.33 and it works now.

**Comment by StarWolf3000** [comment]
I just ran the installer again and the menu reappeared.

**Comment by Shadow-386** [comment]
> I just ran the installer again and the menu reappeared.

Yeah, it got updated and thanks for informing. It works now and to those who don't know download the version v1.1.1.

**Comment by tropicaaal** [comment]
This is not an issue with the installer itself.

**Comment by synkquin** [comment]
Same problem here

<img width="244" height="662" alt="Image" src="https://github.com/user-attachments/assets/6590a177-5b30-4e37-984e-b6da1937a562" />

**Comment by xronuku** [comment]
> Здесь та же проблема
> 
> <img alt="Изображение" width="244" height="662" src="https://private-user-images.githubusercontent.com/218315233/480697260-6590a177-5b30-4e37-984e-b6da1937a562.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4ODE3MjAsIm5iZiI6MTc1NTg4MTQyMCwicGF0aCI6Ii8yMTgzMTUyMzMvNDgwNjk3MjYwLTY1OTBhMTc3LTViMzAtNGUzNy05ODRlLWI2ZGExOTM3YTU2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQxNjUwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDgyOWU3OTAyMjE3YjE0MjgwYjUzN2RmODk4MzgxNjRmNGE3YzlhZTRlNTk3YWYzOTVmYjBmMTc3NTc2NmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f05XkPHzT5-gVkpDtakNhju24i1ehgB3fTxC_ZLWjuA">

у меня та же проблема
