### ISSUE TITLE
Installer fails on last step of installation on both Kubuntu and KDE Neon

### ISSUE THREAD

**Issue by RealDoigt** [BetterDiscord/Installer#133]
**Describe the bug**
As the installation nears completion, the KIO Client will launch a pop-up telling the user that a script cannot be executed "for security reasons" in that "context". This has the apparent effect of cancelling the installation. I used a fresh install of both systems. All they had newly installed was Discord.

**To Reproduce**
1. Use either Kubuntu or KDE Neon
2. Download the BetterDiscord Installer app image.
3. Execute the app image.
4. Follow all normal steps for installation (accept liscence terms, click install, choose first install method, next and wait for it to be done)

**Expected behavior**
A successful installation.

**System Information:**
- Discord Version: Latest stable as of yesterday.

**Comment by ObserverOfTime** [comment]
How are you executing the AppImage? What version of KDE are you on?

**Comment by RealDoigt** [comment]
> How are you executing the AppImage? What version of KDE are you on?

Yes. I don't know which version of KDE I was using, I think Kubuntu uses 5.21 but I'm not sure. The Neon site doesn't say which version of KDE they ship the distro with.

**Comment by RealDoigt** [comment]
sorry I accidentally closed this

**Comment by ObserverOfTime** [comment]
Run `plasmashell --version` and answer my other question too.

**Comment by RealDoigt** [comment]
Oh sorry, I misread, I thought you typed "are you executing the AppImage", sorry if I seemed rude! I ran the app image by double clicking it after making sure it was executable in both cases.

I have since deleted KDE Neon because I was running out of space to test other distros (I was also having other problems with it, like discord stopped working and graphical glitches galore, which may or may not be related to this bug in that case), but results for Kubuntu of the above command is: 5.21.4 (do note that I have since ran multiple updates, so I don't know if the version has changed). 

By the way, I have managed to install BetterDiscord on Kubuntu. All that is different in both attempts is that the failed attempt was in a VM (virtual box) while the successful attempt was installed on a real machine. However it's strange because before that, KDE Neon was also installed on a real machine and yet it had the same error as Kubuntu on VM, so I suspect that while I initially thought the two errors were related, they may not be after all.

**Comment by ObserverOfTime** [comment]
Does it work if you launch the AppImage from a terminal instead?

**Comment by RealDoigt** [comment]
I did try at the time. I found out I need to include the option --no-sandbox, which should definitely be documented somewhere because the error message is not always telling you it's missing. It had the same effect. Running from terminal with sudo also doesn't work.

**Comment by ObserverOfTime** [comment]
This might be related to rauenzi/BetterDiscordApp#694 but that shouldn't occur at the last step.

P.S. You shouldn't run random software with `sudo`.

**Comment by RealDoigt** [comment]
The issues don't look the same to me. Also betterdiscord is something I trust, I wouldn't consider it random software. Do you?

**Comment by ObserverOfTime** [comment]
It's almost always a bad idea to use `sudo` while troubleshooting, not only because it might grant root access to potentially malicious software, but also because it's more likely to break things further rather than fix them (which often happens with [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl/issues?q=label%3Auser%3Apermissions)). The general rule of thumb is: if you don't know why you might need `sudo` to run a command, you shouldn't do it.

Anyway, if this installer doesn't work, you can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl) now that it has been updated.

**Comment by RealDoigt** [comment]
Ok so, just to clarify a few things. I don't need your advice on that, those were test installations that were temporary and I knew what I was getting into and what I was doing. It feels like I'm being attacked and it's not cool, back off. Also I'm not trying the fix the issue. I'm testing several distros a day and yes it's a weird hobby, I'll understand why you're confused, but the point is, there is nothing I can do now because I've already made some space to experiment with other toys. All I wanted to do is report my findings so that the dev may become aware of the issue and what unfolded so he can recreate the conditions and fix the bug if he wants to. That is all.

I will now no longer reply unless if it's for further questions on the issue itself.

**Comment by Soggy-Pancake** [comment]
using the --no-sandbox option worked for me! I kept getting an error saying the gpu process wasn't usable in the terminal.  Im using plasma version 5.24.5

**Comment by ColinTimBarndt** [comment]
This issue also exists on Ubuntu 22.04 and Pop 22.04. It works on my Laptop which uses AMD graphics. This has probably something to do with Nvidia graphics drivers

Edit: Might be related to #247

**Comment by RealDoigt** [comment]
My desktop uses AMD graphics as well, so it's not related to Nvidia. At least not in my case. Though, it's been a while since it happened and I think something changed that fixed the issue because my main is KDE Neon and before that it was Kubuntu for a while and the error never happened again.
