### ISSUE TITLE
Ubuntu Discord 0.0.15 BD no longer works

### ISSUE THREAD

**Issue by AmyClaraRose** [BetterDiscord/Installer#134]
Describe the bug
im using Discord on Ubuntu 21.04 and just updated to 0.0.15 and BD can no longer detect it as discord is no longer under .config folder in home directory also with manual install it says javascript error

To Reproduce

Install Latest Version of discord
Install BetterDiscord (Does not find Discord installed)
Manually find Discord to install
Launch Discord javascript error saying it cant find betterdiscord.asar

Expected behavior
A successful installation.
A successful Boot Up

System Information:

Discord Version: Latest stable as of yesterday.

**Comment by ObserverOfTime** [comment]
> discord is no longer under .config folder in home directory

Where is it then?

**Comment by AmyClaraRose** [comment]
.var/apps

**Comment by AmyClaraRose** [comment]
If I install discord via the Deb package config folder does have a discord folder if installed via software manager it does not have a folder under config

**Comment by ObserverOfTime** [comment]
Your software manager uses flatpak which is not supported by this installer.
You can use [`betterdiscordctl`](https://github.com/bb010g/betterdiscordctl) instead and it should work.

**Comment by AmyClaraRose** [comment]
BetterDiscordctl couldn't detect it as well I tried all options before posting here and software manager I wasn't using flatpak version

**Comment by ObserverOfTime** [comment]
Run `betterdiscordctl -v --d-install flatpak install` and post the output if it doesn't work after restarting Discord.
