### ISSUE TITLE
Wrong version sorting

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#138]
**Describe the bug**
Wrong version sorting may result in older version being chosen by default.

https://github.com/BetterDiscord/Installer/blob/17db962e0b11232b610cde9f1fa3d4f75228c2f9/src/renderer/actions/paths.js#L13
https://github.com/BetterDiscord/Installer/blob/17db962e0b11232b610cde9f1fa3d4f75228c2f9/src/renderer/actions/paths.js#L23

```js
["0.0.2", "0.0.19", "0.0.15", "0.0.16"].sort().reverse()[0];
//"0.0.2"
["0.0.2", "0.0.19", "0.0.15", "0.0.16"].sort().reverse()
//["0.0.2", "0.0.19", "0.0.16", "0.0.15"]
```
this is not how to sort versions. PR inbound tomorrow hopefully. (it's past 8am and I need sleep)

**Comment by zerebos** [comment]
Merged
