### ISSUE TITLE
Linux installer link 404s

### ISSUE THREAD

**Issue by asorel1942** [BetterDiscord/Installer#14]
The link to the .appimage file for the installer on the main page is incorrect, and returns a 404 error, requiring users to https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta and download the file from there.

**Comment by Pukimaa** [comment]
Same issue for me

**Comment by Tropix126** [comment]
Currently looking into this. It's likely because the beta tag was marked as a "pre-release". While this is true, i've unmarked it. We'll see in a few minutes if this was the problem.

**Comment by Tropix126** [comment]
This has been fixed.

**Comment by ObserverOfTime** [comment]
`/releases/latest` does not include pre-releases. You have to link to the actual tag in that case.
