### ISSUE TITLE
Not able to install on MacOS, identity of developer cannot be confirmed

### ISSUE THREAD

**Issue by sivert-io** [BetterDiscord/Installer#145]
**Describe the bug**
"File Can’t be Opened Because the Identity of the Developer Cannot be Confirmed"

**To Reproduce**
1. Download latest installer-package from release
2. unzip .zip-file
3. Open BetterDiscord.app

**Expected behavior**
I expect that an installer-window will open.

**Screenshots**
![bilde](https://user-images.githubusercontent.com/6785315/120012379-b62dd000-bfdf-11eb-96cc-0dadab6ddca4.png)
Sorry, the text in the image is in Norwegian.

**System Information:**
 - OS: MacOS Big Sur 11.4
- Discord Version: Stable

**Additional context**
Running on MacBook Pro 13-inch 2020

**Comment by wlxddd** [comment]
When will this be fixxed?
Got this too btw.

**Comment by tropicaaal** [comment]
This is not a problem with the installer, but rather an intentional macOS security feature.

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
