### ISSUE TITLE
Install after Repair refers to the Installation process as Repair

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#148]
**Describe the bug**
Installing after repair shows starting `Starting Repair...` and `Repair completed!` instead of saying `Install`.

**To Reproduce**
Start the repair process on any discord version.
Click that you wish to install in the dialog.
Look a the installation log

**Expected behavior**
The installer should call it installation instead like a regular installation, or not clear the logs between the processes while omitting the Repair completed! from the actual repair as well as the Starting Repair... from the installation

**~~Screenshots~~ Logs**

> Starting Repair...
> 
> Creating required directories...
> :white_check_mark: Directory exists: C:\<User>\HOME\AppData\Roaming\BetterDiscord
> :white_check_mark: Directory exists: C:\<User>\HOME\AppData\Roaming\BetterDiscord\data
> :white_check_mark: Directory exists: C:\<User>\HOME\AppData\Roaming\BetterDiscord\themes
> :white_check_mark: Directory exists: C:\<User>\HOME\AppData\Roaming\BetterDiscord\plugins
> :white_check_mark: Directories created
> 
> Downloading asar file
> :white_check_mark: Package downloaded
> 
> Injecting shims...
> Injecting into: C:\Users\<User>\AppData\Local\Discord\app-1.0.9002\resources
> :white_check_mark: Injection successful
> :white_check_mark: Shims injected
> 
> Restarting Discord...
> Attempting to kill Discord
> :white_check_mark: Discord not running
> :white_check_mark: Discord restarted
> 
> Repair completed!

**System Information:**
 - OS: All
- Discord Version: All

**Additional context**
Noticed while trying to provide support for a user. Was very confused for a minute because I expected the logs from the repair.

**Comment by zerebos** [comment]
I believe this was intentional as per @Tropix126
