### ISSUE TITLE
Discord installation not detected in ProgramData

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#149]
**Describe the bug**
Discord sometimes seems to install it's files in `%ProgramData%\%username%\<Discord variant>\app-<hostversion>`, where it will not be detected.

**To Reproduce**
I'd like to know too, because it doesn't always do that and people report that the problem is fixed when reinstalling Discord.

**Expected behavior**
The folder should be detected correctly.

**System Information:**
 - OS: Windows
- Discord Version: All, probably (reported cases are on Stable and Canary)

**Additional context**
On BD1: https://discord.com/channels/86004744966914048/119918741516451840/848343507127107604

**Comment by dav1312** [comment]
This should be fixed now in development

**Comment by Abigigi** [comment]
l'installation ne marche pas
