### ISSUE TITLE
Check for installer updates

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#151]
**Is your feature request related to a problem? Please describe.**
There are already a couple of fixes for the installer open as pull requests. But we can't know what changes Discord plans on implementing next. In order to reduce a rush to the suppport server the when the installer breaks in a future Discord update it could check for installer update itself.

**Describe the solution you'd like**
Using GitHub's releases API check for the newest version. If there is one open a message box asking you if you want to download the update, If you do you it either directly opens the browser download url or maybe the relesae web url. If the update check fails it should fail silently.

**Describe alternatives you've considered**
Auto-Updating but that would just end up replacing the exe anyway, which might also be problematic when it's running.

**Additional context**
Currently one of the changes that would require an installer update is that sometimes discord installs to C:\ProgramData

**Comment by Legitti** [comment]
I was just thinking about this as I was downloading it again. Please make it happen.

**Comment by QbDesu** [comment]
There is no reason to download it over and over, there hasn't been an update to the installer since it's initial release. There is a PR for this already. This won't change anything about having to run the installer every couple discord updates.

**Comment by Legitti** [comment]
> There is no reason to download it over and over, there hasn't been an update to the installer since it's initial release. There is a PR for this already. This won't change anything about having to run the installer every couple discord updates.

Yeah, discord update brake it for me so I had to re-install to fix that.

**Comment by tropicaaal** [comment]
> Yeah, discord update brake it for me so I had to re-install to fix that.

The installer automatically downloads the latest version of BD regardless. There's no need to redownload it whenever you want to reinstall BD. This specific issue is regarding actual updates to the installer itself.

**Comment by QbDesu** [comment]
Exactly, only changes like the recent one that caused the need for an updated installer are affected by this. This won't eliminate the need to run the installer again every couple of Discord updates.

Because the corresponding PR has been merge already I'm closing this.
