### ISSUE TITLE
New installer mentions it is discontinued, prompting to use new installer

### ISSUE THREAD

**Issue by XDelta** [BetterDiscord/Installer#152]
**Describe the bug**
I received the message "The version of BetterDiscord you are using has been discontinued. Please reinstall using the new installer found here: https://github.com/BetterDiscord/Installer/releases/latest", downloaded it and installed, only to get the same message about that version being discontinued. It does appear it is changing versions when checking settings so it is doing something.

The new installer seems to set up
```
Stable 86482 (263b26b)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
```

trying the switch to beta in settings shows me
"There is an update available for BetterDiscord's Injector (1.1.1).
You can either update and restart now, or later."
```
Stable 86482 (263b26b)
BD 1.0.0 (086482f)
Host 0.0.309
Injector 0.6.2
```

Following that above update to 1.1.1 seems to upgrade to 
```
Stable 86482 (263b26b)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
```
the same as the new installer.

Additionally I've attempted repair the install use the repair option in the new installer for the same result.

**System Information:**
 - OS: Windows 10 64-Bit (10.0.19042)
- Discord Version: Stable 86482 (263b26b)

**Comment by dav1312** [comment]
**You used an old installer** (not the one found in this repo)
**Download the new installer** from [here](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Windows.exe) or [here](https://betterdiscord.app/)

**Comment by XDelta** [comment]
I have used the one from this repo and specifically the one you have just linked. Same issue. I mentioned so in the initial post. I have also used the download link from https://betterdiscord.app/ which provides the exact same installer.

**Comment by dav1312** [comment]
Still, u seemed to have used an old installer at some point, since ur BD version is 0.3.5. 
Delete the BD folder entirely and reinstall using the latest installer.
Also, you should reinstall discord itself before doing that since you are still in 0.0.309 instead of 1.0.9002.
