### ISSUE TITLE
Themes not appearing in BetterDiscord, even though in theme folder.

### ISSUE THREAD

**Issue by xaxa-0x3F** [BetterDiscord/Installer#154]
**Describe the bug**
Themes not loading in discord to be selected even while they're in my theme folder.

**To Reproduce**
Open better discord, add a theme to your theme folder, watch it not load in

**Expected behavior**
I expected my theme to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/74951182/120520845-e7205300-c399-11eb-9b8c-a44d2a1bf8af.png)
**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**
This has never happened before and, yes I tried editing the file to be css as well and that didn't change anything.

**Comment by dav1312** [comment]
# **This is NOT an issue with the installer**
**You** just **don't know how to install themes** properly.
Themes need to end with `.theme.css` or `.theme` depending if you have file extensions enabled or not.

**Comment by xaxa-0x3F** [comment]
SORRY IM SORRY. I didn't know im sorry.
