### ISSUE TITLE
Discord prompts "Attempt to install host that is currently running" error.

### ISSUE THREAD

**Issue by xaxa-0x3F** [BetterDiscord/Installer#156]
**Describe the bug**
Discord prompts "Attempt to install host that is currently running" error.

**To Reproduce**
Install the most recent better discord installer, close the new instance, try opening again.

**Expected behavior**
Expect my discord to open normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/74951182/120750131-74af9000-c4cb-11eb-93e8-3bfe48d62ca1.png)

**System Information:**
 - OS: 10
- Discord Version: stable

**Additional context**
Didn't have this error on my last pc.

**Comment by KutayTasci** [comment]
I have the same error and can't fix it. I just formatted my pc and cannot install discord again.

**Comment by LaurentOngaro** [comment]
same error for me with the last version (1.0.9158)

![image](https://github.com/user-attachments/assets/8b179854-df12-4472-9f8f-21cbefa2f01d)

**Comment by JeanneD4RK** [comment]
Installed successfully through MS Store.

`winget install discord --source msstore`
