### ISSUE TITLE
Canary discord issue

### ISSUE THREAD

**Issue by czSmoG** [BetterDiscord/Installer#158]
Hi!
For unknow reason
my betterdiscord stopped injecting to my canary discord
![DiscordCanary_ofylQbBmad](https://user-images.githubusercontent.com/84601571/120807697-81be9480-c548-11eb-9f4f-d5793a344a0c.png)
i dont really wanna switch on classic discord, or discord FTB
I tried to repair better discord

**Comment by dav1312** [comment]
Keep track of this issue
https://github.com/rauenzi/BetterDiscordApp/issues/821
