### ISSUE TITLE
Text + Gif emoji

### ISSUE THREAD

**Issue by BorisDmv** [BetterDiscord/Installer#159]
**Describe the bug**
When sending message with text + gif emoji it gives link of the emoji

**To Reproduce**

**Expected behavior**
It should be text and gif emoji without the link

**Screenshots**
https://gyazo.com/aac810857a8b383e600213c9e68652af

**System Information:**
 - OS: Windows 10
- Discord Version: Stable 86782 (3d650d1)

**Additional context**

**Comment by dav1312** [comment]
# This is NOT an issue with the installer

When sending text and a GIF link in the same message Discord always shows the link. This has **nothing** to do with BetterDiscord.
If you want Discord to hide the link, send it in a different message.
