### ISSUE TITLE
EACCES: permission denied, mkdir 

### ISSUE THREAD

**Issue by ARDANFRENDS** [BetterDiscord/Installer#164]
**Describe the bug**
I cant install BD, appearing this error EACCES: permission denied, mkdir 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2021-06-13 at 12 18 13](https://user-images.githubusercontent.com/85816493/121795235-6edf4a80-cc41-11eb-9d04-8e4b153b2551.png)

**System Information:**
 - OS: mac os
- Discord Version:Stable

**Additional context**

**Comment by dav1312** [comment]
Reinstall Discord

**Comment by zerebos** [comment]
See above
