### ISSUE TITLE
A fatal javascript error occured

### ISSUE THREAD

**Issue by Marielek** [BetterDiscord/Installer#165]
**Describe the bug**

![discord 3](https://user-images.githubusercontent.com/85822028/121799536-fc646f80-cc2c-11eb-9d71-5dc81b0b2414.png)

![discord 4](https://user-images.githubusercontent.com/85822028/121799546-0be3b880-cc2d-11eb-9830-bdb31b3679ff.png)

Could someone explain me step by step how to fix it?
**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by ghost** [comment]
Please have a look on https://github.com/rauenzi/BetterDiscordApp/issues/821

**Comment by dav1312** [comment]
> Please have a look on [rauenzi/BetterDiscordApp#821](https://github.com/rauenzi/BetterDiscordApp/issues/821)

@JavaMeme  his issue is not related to that

**Comment by ghost** [comment]
> > Please have a look on [rauenzi/BetterDiscordApp#821](https://github.com/rauenzi/BetterDiscordApp/issues/821)
> 
> @JavaMeme his issue is not related to that

I didn't see that. Just saw JavaScript error and linked it, I'm sorry

**Comment by Marielek** [comment]
@JavaMeme True, my mistake is a little different from that, but thank you for trying to help. Sorry for all grammar mistakes, but I use a translator
![discord 5](https://user-images.githubusercontent.com/85822028/121815345-4e7db300-cc76-11eb-9cdc-eb330289b4f8.png)

**Comment by zerebos** [comment]
Reinstall Discord
