### ISSUE TITLE
BD Crashing After Update

### ISSUE THREAD

**Issue by SM0KEX** [BetterDiscord/Installer#17]
I updated better discord, and it keeps crashing. Also, I can't even go to the settings on my plugins.
![db0fc71443dfbadd12ecaad034e1ed43](https://user-images.githubusercontent.com/66188026/113296932-10543280-92c8-11eb-893e-bf160da88d28.png)

**Comment by Goroseitto** [comment]
Yeah, I'm getting this error:
![image](https://user-images.githubusercontent.com/81758084/113297939-a3de3100-92d1-11eb-9b34-b588617d90e4.png)

**Comment by Tropix126** [comment]
> Yeah, I'm getting this error:
> ![image](https://user-images.githubusercontent.com/81758084/113297939-a3de3100-92d1-11eb-9b34-b588617d90e4.png)

This is not the same installer linked in this repository. Get the latest version from [here](https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta).

**Comment by Tropix126** [comment]
As for the main issue, this isn't directly related to the installer itself so it should probably be reopened at https://github.com/rauenzi/BetterDiscordApp/issues, but I can provide a few pointers.

- Try wiping your plugins folder.
- Try completely reinstalling discord (delete %appdata%/Discord and %localappdata%/discord), then completely reinstsall everything.

**Comment by NachiketBidarkundi** [comment]
> As for the main issue, this isn't directly related to the installer itself so it should probably be reopened at https://github.com/rauenzi/BetterDiscordApp/issues, but I can provide a few pointers.
> 
> * Try wiping your plugins folder.
> * Try completely reinstalling discord (delete %appdata%/Discord and %localappdata%/discord), then completely reinstsall everything.

How do u do that on MACos???
