### ISSUE TITLE
[Feature] custom plugin/theme folder location

### ISSUE THREAD

**Issue by pozhiloy-enotik** [BetterDiscord/Installer#172]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add an option in the settings somewhere to set a custom plugin/theme folder location

instead of using "%appdata%/BetterDiscord/plugins" you could change it in the settings to use another folder like "Downloads/plugins" or "Desktop/plugins" or wherever you feel like putting it

**Describe alternatives you've considered**
making symbolic links(is this really the solution?)

**Comment by zerebos** [comment]
This is something that BD itself would need to handle (tracked under https://github.com/BetterDiscord/BetterDiscord/issues/539). You can currently use symlinked folders, those do work and that's what I use locally.
