### ISSUE TITLE
Set time limit to avoid getting stuck

### ISSUE THREAD

**Issue by dav1312** [BetterDiscord/Installer#173]
**Is your feature request related to a problem? Please describe.**
For some people the installer gets stuck either downloading the asar file (#35 / #137) or attempting to kill Discord (#25).

**Describe the solution you'd like**
Add a time limit to those actions, the installer will warn the user with an error and maybe suggest some solutions or alternatives.

**Comment by QbDesu** [comment]
This is a problem with the phin node http request library. It would be better not to work around it but rather having this fixed. There has been a pull request for it for more about 2 months now without any reaction by the mainainers which would cause me to look for alternatives at this point. https://github.com/ethanent/phin/issues/59

**Comment by zerebos** [comment]
The main reason for this was fixed with the last release
