### ISSUE TITLE
License Checkbox (v1.0.0-hotfix)

### ISSUE THREAD

**Issue by dav1312** [BetterDiscord/Installer#177]
**Describe the bug**
The license checkbox doesn't work.

**To Reproduce**
1. Open the installer
2. Try clicking the installer checkbox

**Expected behavior**
Clicking the checkbox should work fine, not just the text.

**Screenshots**

https://user-images.githubusercontent.com/63931154/125085947-6b69a280-e0cb-11eb-928d-4c9800811e58.mp4

**System Information:**
- OS: Windows

**Comment by tropicaaal** [comment]
This has been fixed on the `dev` branch as of 83d0beee8fe87d0ebb6fa92c4bd15c58dfc9ac56.

**Comment by zerebos** [comment]
This has been fixed in the new release
