### ISSUE TITLE
Thoughts about replacing phin

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#179]
**Describe the bug**
phin won't follow redirects by default which broke the download after the App repo was moved to the organization. This is a lesser problem, after the hotfix but might still be worth looking into and fixing anyway, just in case. I wouldn't blame this on phin but it prompts the need for some changes

Here comes the bigger question though: While we are at it we should maybe consider changing over from phin to another library, 

Phin has this nasty bug where it will never resolve/reject a promise when the server aborts the connection, which Github sometimes does. Often enough to be significant in my opinion.
The bug was reported in December of last year There is is a pull request that should apparently fix it from 3 months ago. The maintainers didn't even reply to either the issue or the PR until now.
And no unfortunately that bug was not quietly fixed in the mean time and it's still present in the latest version.

If we were to change I would suggest node-fetch as an alternative, I'm gonna guess there is a reason why you didn't wanna use the electron browsers built-in version of fetch, if I would have to guess I'd probably say CSP stuff. 

**To Reproduce**
See non-hotfixed installer.

**Expected behavior**
Follow redirects.

**System Information:**
 - OS: all
- Discord Version: all

**Additional context**
Issue about the infinite asar download: https://github.com/BetterDiscord/Installer/issues/173
phin issue about the infinte promise on aborted connections https://github.com/ethanent/phin/issues/59

**Comment by zerebos** [comment]
> phin won't follow redirects by default which broke the download after the App repo was moved to the organization. This is a lesser problem, after the hotfix but might still be worth looking into and fixing anyway, just in case. I wouldn't blame this on phin but it prompts the need for some changes

`followRedirects` was added in https://github.com/BetterDiscord/Installer/commit/384bef63e9d64a53fb5891a7ba30199645d3c0d7


> If we were to change I would suggest node-fetch as an alternative

It would either `node-fetch` or `axios`


> I'm gonna guess there is a reason why you didn't wanna use the electron browsers built-in version of fetch, if I would have to guess I'd probably say CSP stuff

That is definitely one reason
