### ISSUE TITLE
the download links mess

### ISSUE THREAD

**Issue by 1mad1** [BetterDiscord/Installer#18]
Please fix the download link and the version number confusion.
First I got a update available popup  
As you see, it says a update available 1.0.0
![Capture](https://user-images.githubusercontent.com/52380483/113306060-ba59ac00-9314-11eb-9d49-44541da4cef1.PNG)
Suggestion: I suggest changing “1.0.0” to “1.0.0-beta”.
I clicked “Update Now”, but it couldn’t as you see.
 ![2](https://user-images.githubusercontent.com/52380483/113306271-f55bdf80-9314-11eb-8efb-19ba62b4f53f.PNG)

I clicked “Download Installer” Link which is https://github.com/rauenzi/BetterDiscordApp/releases/latest which redirects to https://github.com/rauenzi/BetterDiscordApp/releases/tag/v1.0.0 as you see there is a note of new Installer Releases and download link for v1.0.0 (which is actually v1.0.4 I mean BandagedBD_Windows.exe 112KB)

Suggestion: change “Download Installer” link to https://github.com/BetterDiscord/Installer/releases/ 
 ![233](https://user-images.githubusercontent.com/52380483/113306100-c5acd780-9314-11eb-8e0c-cf6d6644569e.PNG)

Suggestion change v1.0.0 to v1.0.4, or just delete it.
I downloaded “BandagedBD_Windows.exe 112KB” and opened, as you see  
![123111111](https://user-images.githubusercontent.com/52380483/113306744-761adb80-9315-11eb-8871-2441b1f0a332.PNG)

I clicked yes it brings to https://github.com/rauenzi/BBDInstaller/releases/download/v1.0.5/BandagedBD.exe i downloaded it and installed, yet I still get a update available popup like the first image, then I realized that I have to download the beta installer from(https://github.com/BetterDiscord/Installer/releases/)
The result:
![3](https://user-images.githubusercontent.com/52380483/113306369-115f8100-9315-11eb-8150-04b31e67e050.PNG)

 
Suggestion change “v1.0.0” to “v1.0.0-beta”.

Conclusion: There are 3 repo links
https://github.com/rauenzi/BetterDiscordApp/releases  (v1.0.0 download(it's actually 1.0.4) + v.1.0.0-beta link note)
https://github.com/rauenzi/BBDInstaller/releases  (v1.0.5 download)
https://github.com/BetterDiscord/Installer/releases  (v1.0.0-beta download)
Suggestion: archive the first repo link. For the second repo link add a note that there is a new beta installer and update the links or whatever.

and since there are three repo, i don't if i should open a issue here or there or there.

**Comment by Tropix126** [comment]
Yeah, this is something I'm hoping to fix once our new site is released. The older BBDInstaller repository will be archived soon and redirect to this one, however. As for the update notices, all of these are present on older versions of BD only, and once most people are on the latest rewrite of BD will become less common of an issue.
The main problem here is the old .net website linking to a very outdated repo. Sadly, the owner of the site (original maintained of BD) is extremely difficult to contact, so all we can do there is wait for the new site to come out.

**Comment by L-m-b** [comment]
Just get a new domain, its a long name so it should be fairly cheap (like 5/year) and get a multi-domain ssl, or if jiiks already has one see if you can get access from them, then you can use cloudflare or whatever other reverse proxy you want and host it yourselves.
I don't think anyone would mind using a different link when the other one has more wrong with it than a different suffix.

**Comment by L-m-b** [comment]
![image](https://user-images.githubusercontent.com/30617839/113365917-72359a80-93a3-11eb-93ba-0758937c3de8.png)
nevermind get this domain

**Comment by Dark-Duty** [comment]
![image](https://user-images.githubusercontent.com/81814050/113418322-298adb00-93bd-11eb-8ee7-39f5e5ec4e3f.png)
using the new links make these uncompleted note files that fully complete for some reason 
![image](https://user-images.githubusercontent.com/81814050/113418393-50e1a800-93bd-11eb-8407-3f67ae608a26.png)

**Comment by Tropix126** [comment]
> Just get a new domain, its a long name so it should be fairly cheap (like 5/year) and get a multi-domain ssl, or if jiiks already has one see if you can get access from them, then you can use cloudflare or whatever other reverse proxy you want and host it yourselves.
> I don't think anyone would mind using a different link when the other one has more wrong with it than a different suffix.

The new site will be on a new domain.

**Comment by rauenzi** [comment]
- The old installer repo has been archived with a notice redirecting here.
- The old version of BD with that false update notice will now redirect here as well.
- The BD client repo has updated old links to redirect here as well.

As for the website betterdiscord.net I do not have control over it and getting in touch with Jiiks to make changes is... difficult. We have an updated website on a separate domain coming soon which will take over as the official site.
