### ISSUE TITLE
Installer won't let me accept the license agreement

### ISSUE THREAD

**Issue by Postal-Servis** [BetterDiscord/Installer#180]
The check box simply doesn't get checked. Clicking it does nothing, and the "Next" button stays grayed-out and unclickable, even after restarting and redownloading the installer. Using Windows 10 Pro on an old lenovo W500 laptop.

**Comment by QbDesu** [comment]
It's a bug in the current hotfix version of the installer. You can click the "I accept the license" text label next to the checkbox to check it though.

**Comment by Postal-Servis** [comment]
> It's a bug in the current hotfix version of the installer. You can click the "I accept the license" text label next to the checkbox to check it though.

Thank you!
