### ISSUE TITLE
Issues with Workaround Installer Builds

### ISSUE THREAD

**Issue by DareDeveloperbruh** [BetterDiscord/Installer#181]
**Describe the bug**
The Linux AppImage build is pushing the same "assets" error as before, however a build I have made is functional. The Mac installer appears to cause an error in which the themes and plugins folders are not made, resulting in a Finder error. It's unclear if a rebuild will fix this as Mac's ditto tool is needed for a successful build.

**To Reproduce**
Download .AppImage or Mac .zip; the Linux installer will fail and the Mac installer does not make needed folders, like plugins and themes.

**Expected behavior**
Linux and Mac build should complete and create all needed files for normal functions.

**System Information:**
 - OS: Linux/Mac
- Discord Version: Latest Stable

**Additional context**
Downloading the source code .zip and building for Linux resulted in a functional installer that worked on my machine for updating and installing BetterDiscord. BetterDiscord v1.2.0, Latest Stable Discord, Manjaro Linux

**Comment by zerebos** [comment]
I have updated the linux build. the mac issue is not that the folders are not made, it is an issue with how BD is cloning the process object. But that is BD proper and not the installer.
