### ISSUE TITLE
Disable all addons on repair

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#189]
**Is your feature request related to a problem? Please describe.**
Some people's first instinct when BetterDiscord is not working is to run repair. The number of times I've seen people falsely advise others to run the repair option when there is a plugin issue is alarming, and a lot of users do it by themselves even if they aren't advised by anyone. Other times people advise using the repair option when a simple install would be enough.
Most of the time the repair option does not provide any added value and I haven't seen more than 1 or 2 cases where is was the proper solution. So how about we change that?

**Describe the solution you'd like**
The repair option should disable all plugins. A simple way to do that would be to just delete the `plugins.json` and `themes.json` files. This way when people actually do run it to prevent addon issues it's actually helpful.
I think it's easier to change the installers repair option to what the user expects than trying to change the way the user acts.

**Comment by dakshcs** [comment]
could i have the plugins and themes directory path for mac? I'm having the same problem and repairing/removing BD doesen't fix it.

**Comment by zerebos** [comment]
We chose to only disable plugins
