### ISSUE TITLE
Download speed very slow

### ISSUE THREAD

**Issue by rgeorge04** [BetterDiscord/Installer#191]
Please fix your server, the packages downloads very slow (50kb/s), it takes 20min for a 60mb to be downloaded

**Comment by dav1312** [comment]
The installer and the asar are both downloaded from Github, not from a "Betterdiscord server"

**Comment by rgeorge04** [comment]
> The installer and the asar are both downloaded from Github, not from a "Betterdiscord server"

i don't know about that, github seems to download other packages fine. I am just trying to help, so other people don't experinece this issue

**Comment by aspiers** [comment]
Filed #192 as for me it's not just slow, it hangs on the download forever.
