### ISSUE TITLE
themes are not working even when activated

### ISSUE THREAD

**Issue by gloomykid** [BetterDiscord/Installer#193]
**Describe the bug**
Activate theme is not shown, discord looks exactly like without the better discord feature.

**To Reproduce**
1. go to settings > better discord/themes > activate your theme > doesn't show the theme

**Expected behavior**
i expected to see the theme? 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13604430/127195163-51dc0762-2654-455a-b820-4a2ab9cd76ce.png)

**System Information:**
 - OS: windows 7 professional
- Discord Version: Stable 91289, BetterDiscord 1.2.0, Host 1.0.9002 Windows Server 2008 R2 / 7 64-Bit (6.1.7601)

**Additional context**
it worked until maybe 1-2 days ago?

**Comment by dav1312** [comment]
### This is not an issue with the BetterDiscord Installer.
Gibbu changed some things in his repos. You need to either update the import links or redownload the theme from the website.

**Comment by gloomykid** [comment]
Alright, thank you, wasn't aware of it, sorry!
