### ISSUE TITLE
[Suggestion] Change the server invite link in the installer when it fails

### ISSUE THREAD

**Issue by identity7** [BetterDiscord/Installer#194]
**Is your feature request related to a problem? Please describe.**
The server invite link in the installer leads to the offtopic channel instead of announcements or support.

**Describe the solution you'd like**
The invite link to be changed to https://discord.gg/bd-app so that they join into announcements

Or one for support if that is possible

**Additional context**
This is the current link that is in the installer
https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by Overimagine1** [comment]
The problem with that is that most of our boosts come from people who use the epic games nitro, so when the vanity expires someone could use the vanity for something bad. Maybe they should just create a new permanent invite and use that instead.

**Comment by QbDesu** [comment]
There is also https://betterdiscord.app/invite
While using that would have the advantage of being able to update the invite link without updating the installer, I like that the installers link would still be working when the website is down or something.

**Comment by dav1312** [comment]
I like the idea of having different invite links, but changing it to the vanilla invite link is probably not the best idea for the reason Christian explained.
It could be a nice way of tracking where people come from. So you can see if they joined from the readme, from the installer or from the website for example.

**Comment by zerebos** [comment]
Please see the above comments
