### ISSUE TITLE
"You Died" screen when opening discord

### ISSUE THREAD

**Issue by kozu10299** [BetterDiscord/Installer#195]
**Describe the bug**
When trying to open up Discord it starts freezing the screen for a moment and puts it on this "you died" screen.

**To Reproduce**
1. Open discord
2. See error

**Expected behavior**
A successful opening through the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/88409867/128100295-6da3345d-e5b3-472f-9d37-9b849c21f810.png)
**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**
Even when repeatedly updating the plugins on top and repairing the installation it still pops up the "you died" screen

**Comment by dav1312** [comment]
This is not an issue with the installer

**Comment by xMdb** [comment]
Check your plugins folder

**Comment by xNiftu** [comment]
how i had it i was scared lol
