### ISSUE TITLE
[Bug]cannot excute installer

### ISSUE THREAD

**Issue by LPMINO** [BetterDiscord/Installer#196]
**Describe the bug**
When I execute installer, it soon disappears from the Task Manager.

**To Reproduce**
just execute installer. i even tried running as administrator

**Expected behavior**
Normally execute, and install BD

**Screenshots**
https://cdn.discordapp.com/attachments/403405715080740874/873770404798410802/Honeycam_2021-08-08_12-30-26.gif

**System Information:**
 - OS: Windows
- Discord Version: Stable

**Additional context**

**Comment by dav1312** [comment]
Try using this installer
https://bd.zerebos.com/BetterDiscord-Windows-7z.exe

**Comment by LPMINO** [comment]
well, i've already tried. but it doesn't work

**Comment by 123Michal123** [comment]
can someone please help on how to install on iphone

**Comment by dav1312** [comment]
> can someone please help on how to install on iphone

@123Michal123 Betterdiscord is NOT for mobile

**Comment by zerebos** [comment]
Dup of #36
