### ISSUE TITLE
Erro de banner

### ISSUE THREAD

**Issue by Gattin02** [BetterDiscord/Installer#198]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by Gattin02** [comment]
https://discord.com/channels/876875761330581564/876893020979621889/876917701543592036

**Comment by dav1312** [comment]
Please at least fill the form properly.
