### ISSUE TITLE
My BetterDiscord crashes saying "betterdiscord has temporarily disable itself. try removing all your plugins then restart discord"

### ISSUE THREAD

**Issue by BatrleCry1** [BetterDiscord/Installer#200]
I tried to fix betterdiscord using the repair option, but then it says theres a missing "asar" file
and i cant find a solution. I removed most of the plugins, but it still doesnt work. I dont really want to remove the themes tho. Does anyone have a solution to this?

**Comment by Tox1kDEV** [comment]
I too have the same problem

**Comment by Dekirai** [comment]
The newest discord version broke BetterDiscord.
We have to wait for a new BD update.

**Comment by Dekirai** [comment]
[Click here to see the fix for it](https://github.com/BetterDiscord/BetterDiscord/issues/995#issuecomment-901337922)
Follow the fix there, it worked for me.

**Comment by repositoryless** [comment]
The asar/assets issue has been fixed a while already, you need the latest installer from https://betterdiscord.app . About the crashing, you need to redownload ZeresPluginLibrary and BDFDB both from https://betterdiscord.app/plugins .

**Comment by BatrleCry1** [comment]
> 
> 
> The asar/assets issue has been fixed a while already, you need the latest installer from https://betterdiscord.app . About the crashing, you need to redownload ZeresPluginLibrary and BDFDB both from https://betterdiscord.app/plugins .

Thanks! Worked for me!

**Comment by MarkJeronimus** [comment]
Redownloading the js worked, but shouldn't the installer be able to do that?

When I run `betterdiscordctl reinstall`, I get:
> ERROR: Self-upgrading has been disabled.
> If you installed this from a package, its maintainer should keep it up to date.

I did install from the package, but it's not upgrading. Latest is 2.0.1, which is weird because neither BetterDiscord nor Installer have version numbers that high.
