### ISSUE TITLE
Github button leads to wrong URL

### ISSUE THREAD

**Issue by MulverineX** [BetterDiscord/Installer#201]
**Describe the bug**
Clicking the view source button opens https://github.com/BetterDiscord/BetterDiscor (no d).

**To Reproduce**
1. Click on the GitHub button at the bottom left
3. Notice the 404 & typo

**Expected behavior**
Opens to https://github.com/BetterDiscord/BetterDiscord

**Screenshots**

**Additional context**
Very weird behavior as [this line](https://github.com/BetterDiscord/Installer/blob/main/src/renderer/common/SocialLinks.svelte#L3) suggests that it shouldn't happen, as that URL redirects to the correct link when manually used.

**Comment by dav1312** [comment]
This was already fixed in the [development branch](https://github.com/BetterDiscord/Installer/blob/development/src/renderer/common/SocialLinks.svelte#L5)

**Comment by zerebos** [comment]
See above, next release will have this fixed.
