### ISSUE TITLE
Impossible de finaliser l'installation BD

### ISSUE THREAD

**Issue by REDOG47** [BetterDiscord/Installer#206]
Bonjour à tous, je n'arrive pas a installer BD, l'installation s'arrete précisément a la conclusion de l'installation.

Merci pour vos retours 
RED

![image](https://user-images.githubusercontent.com/90039920/131993884-b678cf1f-dc3b-4a80-a0ef-ec8d4f0cf72b.png)

**Comment by dav1312** [comment]
Duplicate of #174
