### ISSUE TITLE
Shortcuts for Vanilla mode

### ISSUE THREAD

**Issue by QbDesu** [BetterDiscord/Installer#207]
**Is your feature request related to a problem? Please describe.**
A lot of people don't realize that BD has the option to start in Vanilla mode.

**Describe the solution you'd like**
A simple start menu entry (on Windows) or `.desktop` file (on Linux) should be created by the installer.

**Describe alternatives you've considered**
Adding a vanilla launch option to the installer itself. Although on least on Linux the installer manage to open Discord after the installtion, at least for me.

**Comment by zerebos** [comment]
I'm not sure this is something we should add especially in the installer.

**Comment by dav1312** [comment]
Maybe adding button inside the bd options that restarts discord with bd disabled.
It could also add a notice telling people how to enable bd again (restarting discord)
