### ISSUE TITLE
New Update breaks betterdiscord

### ISSUE THREAD

**Issue by Demented-Elmo** [BetterDiscord/Installer#209]
**Describe the Bug**
After the new update on PBT, Betterdiscord was uninstalled, and I cannot reinstall it

**To Reproduce**
Update Discord PBT to the latest version

**Expected Behavior**
It will uninstall, and you cannot inject the shims

**Screenshots**
https://cdn.discordapp.com/attachments/872597872472907896/888556630248140920/Screen_Shot_2021-09-17_at_4.29.46_PM.png

**Discord Version**
PBT, Default

**Additional Context**
I have tried literally every other solution, other people are experiencing this same issue

**Comment by OilFreak** [comment]
yeah the new ptb update broke better discord for me too.

**Comment by pickanothername** [comment]
Same exact issue here as well.

Full context:
Discord PTB updated and BetterDiscord stopped launching with it. I used Repair on it and the repair failed, so I updated to the new installer (v1.2.1) and tried again, and it succeeded this time, but now Discord crashes on launch and BD gets disabled.

**Comment by jerbear2008** [comment]
I used the latest installer and selected `Repair` and it fixed it perfectly.

**Comment by Demented-Elmo** [comment]
> I used the latest installer and selected `Repair` and it fixed it perfectly.

On what version? Because it does not work for me.

**Comment by pickanothername** [comment]
Repairs does not work for me still as well, and I also tried removing all of my plugins. This did not fix it either.

**Comment by maicol07** [comment]
@Demented-Elmo PTB Discord

**Comment by Demented-Elmo** [comment]
@maicol07 what do you mean

**Comment by maicol07** [comment]
@Demented-Elmo the PTB version of Discord: [https://support.discord.com/hc/it/articles/360035675191-Discord-Testing-Clients](https://support.discord.com/hc/it/articles/360035675191-Discord-Testing-Clients)

**Comment by Demented-Elmo** [comment]
@maicol07 yeah i know what pbt is, i use it. What do you want me to do?

**Comment by maicol07** [comment]
> @maicol07 yeah i know what pbt is, i use it. What do you want me to do?

Oh, didn't see you meant the launcher version. Sorry, my fault! 😅

**Comment by Demented-Elmo** [comment]
Fixed
