### ISSUE TITLE
Check for updates feature of BetterDiscord beta error

### ISSUE THREAD

**Issue by minhngoc25a** [BetterDiscord/Installer#21]
![image](https://user-images.githubusercontent.com/33834488/113314874-edad3280-9336-11eb-89ed-23d0a978740c.png)

If I hit Update now, a fail message would appear, and there would be a button that takes you to the page to download the installer. The problem is that it links to the Stable installer, not the Beta installer. I'm currently using Beta BetterDiscord.

**Comment by Tropix126** [comment]
See #15.
