### ISSUE TITLE
[Bug] Stuck with Downloading asar. Asar download url is outdated - use repo id instead of repo name

### ISSUE THREAD

**Issue by cpuccino** [BetterDiscord/Installer#211]
**Describe the Bug**
Stuck with "Downloading asar file"

**To Reproduce**
Download the latest installer for Linux in the better discord site

**Expected Behavior**
It should patch discord

**Additional Context**
Did a little bit of debugging, 

The main culprit was `https://github.com/BetterDiscord/Installer/blob/main/src/renderer/actions/install.js#L52` , which returns a github redirect, I'm guessing the main issue is that the url the repo was renamed from `BetterDiscordApp` to `BetterDiscord`

![image](https://user-images.githubusercontent.com/66815398/134002725-64705722-2738-40b2-b4b4-43dfb47295e8.png)

PS: I'm guessing the latest Linux build in the site is outdated cause when i cloned the repo and ran a build, it actually throws an error and it doesn't get stuck with the download phase, whereas the one from the site gets stuck

**Fix**
Can someone update that line to `https://github.com/BetterDiscord/BetterDiscord/releases` instead or better yet, use the repo id instead `105473537` `https://api.github.com/repositories/105473537`

**Note**
Mistakenly created the issue in https://github.com/BetterDiscord/BetterDiscord/issues/1044

**Comment by dav1312** [comment]
The develoment branch has that fixed already. ~~It should be implemented in the next installer release.~~

**Comment by cpuccino** [comment]
> The develoment branch has that fixed already. It should be implemented in the next installer release.

Ah awesome, feel free to close the issue then, 

kinda odd that the repo has been renamed tho without the dev branch being merged back yet - **this is currently breaking installations**, and also I'd suggest using the repo id instead of https://github.com/BetterDiscord/Installer/blame/1bf733dbb989c00ecf17a755ef931fa961195812/src/renderer/actions/install.js, in the unlikely event that the team does decide to rename the repo again

**Comment by zerebos** [comment]
> this is currently breaking installations

The latest release uses the correct URL. https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix

**Comment by zerebos** [comment]
Also just for reference the `/repositories` endpoint using an ID (e.g. `https://api.github.com/repositories/105473537`) is not officially documented in their documentation.

**Comment by cpuccino** [comment]
> > this is currently breaking installations
> 
> The latest release uses the correct URL. https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix

Ah cool then, that must mean the linux appimage in the download page is outdated cause it was not working at all for me, can you guys check that. But ye, I’m not gonna bother creating a new issue for it. Thanks for responding, have an awesome week :)

Awesome project btw, cheers mate 🍻 

ps: that’s been a thing for a decade now lmao, can’t believe they still won’t document it lmao, anyway, it’s not really a big deal cause how often do you even update a repo lol

**Comment by dav1312** [comment]
> Ah cool then, that must mean the linux appimage in the download page is outdated cause it was not working at all for me, can you guys check that.

The website should always download the latest github release of the installer
```js
function downloadBetterDiscord() {
    const releases = "https://github.com/BetterDiscord/Installer/releases/latest/";
    switch (os) {
    case 'Windows':
        return window.location.href = releases + 'download/BetterDiscord-Windows.exe';
    case 'Mac OS':
        return window.location.href = releases + 'download/BetterDiscord-Mac.zip';
    case 'Linux':
        return window.location.href = releases + 'download/BetterDiscord-Linux.AppImage';
    default:
        window.location.href = releases;
    }
}
```

**Comment by cpuccino** [comment]
> > Ah cool then, that must mean the linux appimage in the download page is outdated cause it was not working at all for me, can you guys check that.
> 
> The website should always download the latest github release of the installer
> 
> ```js
> function downloadBetterDiscord() {
>     const releases = "https://github.com/BetterDiscord/Installer/releases/latest/";
>     switch (os) {
>     case 'Windows':
>         return window.location.href = releases + 'download/BetterDiscord-Windows.exe';
>     case 'Mac OS':
>         return window.location.href = releases + 'download/BetterDiscord-Mac.zip';
>     case 'Linux':
>         return window.location.href = releases + 'download/BetterDiscord-Linux.AppImage';
>     default:
>         window.location.href = releases;
>     }
> }
> ```

Ah cool, something else must be wrong then 🤔
