### ISSUE TITLE
BD Crashes Client, Full Reinstall Doesn't Help

### ISSUE THREAD

**Issue by Avakining** [BetterDiscord/Installer#212]
**Describe the bug**
Opening the latest stable version of Discord produces this error message:
> BetterDiscord seems to have crashed your Discord client.
> BetterDiscord has automatically disabled itself temporarily. Try removing all your plugins then restarting Discord.

**To Reproduce**
1. Open Discord
2. Get the error message above

**Expected behavior**
BetterDiscord starts

**System Information:**
 - OS: macOS 12.0 Beta
- Discord Version: 
>Stable 98381 (96e4f5d) 
>Host 0.0.264 

**Additional context**
I've tried removing all plugins/themes, uninstalling/reinstalling Better Discord, removing and reinstalling every Discord-related file then installing BD on that new Discord instance. None of that worked.

**Comment by zerebos** [comment]
This is a BD issue not the installer, please seek help on that repo or server
