### ISSUE TITLE
Virustotal

### ISSUE THREAD

**Issue by Kery5** [BetterDiscord/Installer#22]
![Web capture_1-4-2021_173655_www virustotal com](https://user-images.githubusercontent.com/53485931/113318579-e1ae7a00-9310-11eb-91d2-9b6e316bab46.jpeg)

Can you explain this please?

**Comment by LunarOccultist** [comment]
Yeah what is this, I am uninstalling and waiting to see what the response is before updating.

**Comment by Tropix126** [comment]
This is likely a false-positive. When I upload to VirusTotal, I the crowdsourced rules don't appear. Could you screenshot one of the rulesets?

**Comment by Kery5** [comment]
Sure.
![Web capture_1-4-2021_184122_www virustotal com](https://user-images.githubusercontent.com/53485931/113326419-e88dba80-9319-11eb-9c19-90b28862176b.jpeg)
![Web capture_1-4-2021_18412_www virustotal com](https://user-images.githubusercontent.com/53485931/113326420-e9265100-9319-11eb-9327-7743d120faeb.jpeg)

**Comment by Tropix126** [comment]
Since i'm not entirely familliar with how virustotal operates, and there doesn't seem to be any real documentation around these crowdsourced rules, i've asked the other maintainer (zere) about it, since he manages the more internal electron aspects and install scripts. Will keep you updated. Feel free to check the source code in the time being, it's documented in the readme.

**Comment by Curtis-D** [comment]
It's entirely open source, so whilst there is a small possibility of there being a virus, it's extremely unlikely that Zack (who has been pushing out updates for BD for 2 or so years for free and in his own time) would now decide to add randomware to BD.

It's a false positive and it happens, but if you're worried feel free to check the source or wait until someone who has programming knowledge to check it for you

**Comment by QuantumWarpCode** [comment]
Just to go through these, the YARA rule it matches is designed to detect PlugX in memory by matching roughly 30 bytes that this installer just happens to also place into memory. The Sigma rule for detecting Nibiru seems to be a false match to when BDD installer calls a process with the arguments listed in your screenshot, which happens to contain "-u" "-p" and "2656". The crowdsourced rule doesn't seem to bother to check if that number is at the end or if the argument is exclusively "-u" and not "-use-gpu."

**Comment by Kery5** [comment]
> Just to go through these, the YARA rule it matches is designed to detect PlugX in memory by matching roughly 30 bytes that this installer just happens to also place into memory. The Sigma rule for detecting Nibiru seems to be a false match to when BDD installer calls a process with the arguments listed in your screenshot, which happens to contain "-u" "-p" and "2656". The crowdsourced rule doesn't seem to bother to check if that number is at the end or if the argument is exclusively "-u" and not "-use-gpu."

A user on reddit said the same thing, I was just waiting for someone else to confirm it. [https://www.reddit.com/r/antivirus/comments/mi05py/help_with_this_file/](url)
So it is just a bad written rule, thanks everyone.

**Comment by Tropix126** [comment]
Issue closed unless anything else comes up.
