### ISSUE TITLE
Discord Crashing When Launching

### ISSUE THREAD

**Issue by TheFastRunners** [BetterDiscord/Installer#224]
Whenever I start up discord now, it just loads in all the better discord plugins and themes and then crashes saying this
![image](https://user-images.githubusercontent.com/93170545/138794989-e0e180d9-7a2d-400f-ad13-6a94ac6664f7.png)
Does anyone know how to fix this?

**Comment by dav1312** [comment]
1) Before opening an issue **make sure that you don't have plugins or themes installed**. This is to guarantee that the issue is caused by BetterDiscord.
2) This is the wrong repo to open issues about BetterDiscord
