### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SniperWasTaken** [BetterDiscord/Installer#228]
**Describe the bug**
Okay, soo... Discord crashes everytime i install it.

**To Reproduce**
1. Install it.
2. Then i literally crash it.

**Expected behavior**
It said that i had to install it manually,

**Screenshots**

![dwm_rh1ZGci3lW](https://user-images.githubusercontent.com/56523518/142781025-1165d644-be9e-4dc3-bf3e-01d4852d784d.png)

**System Information:**
 - OS: Windows
- Discord Version: Stable ver.

**Comment by ljcool2006** [comment]
I'm having the same issue. Why is everyone booing him?

**Comment by he1d1** [comment]
Try installing with Discord closed.

**Comment by SniperWasTaken** [comment]
Why did you dislike this in the first place then give me the solution?
