### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by flowxiong** [BetterDiscord/Installer#229]
Starting Install...

Creating required directories...
✅ Directory exists: /Users/xiong/Library/Application Support/BetterDiscord
✅ Directory exists: /Users/xiong/Library/Application Support/BetterDiscord/data
✅ Directory exists: /Users/xiong/Library/Application Support/BetterDiscord/themes
✅ Directory exists: /Users/xiong/Library/Application Support/BetterDiscord/plugins
✅ Directories created

Checking for old MacOS installation...

Downloading asar file
❌ Failed to download package undefined
❌ Cannot read property 'hasOwnProperty' of undefined
**The install seems to have failed. If this problem is recurring, join our discord community for support.**
<img width="447" alt="截屏2021-11-27 上午9 43 22" src="https://user-images.githubusercontent.com/94422913/143664838-0e6ba518-b819-4cc3-ba4b-f6d4a36748b7.png">
How to deal with this problem？THX

**Comment by calify** [comment]
I have the same error, do you have fixed it?

**Comment by 312ing** [comment]
i had the same error but i fixed it, simply clear all files related to discord. uninstall it and remove the data then re-install it

**Comment by dyoga** [comment]
> i had the same error but i fixed it, simply clear all files related to discord. uninstall it and remove the data then re-install it

Didnt work for me. Uninstallled with revo uninstaller and the issue is still there.

**Comment by shoucandanghehe** [comment]
![image](https://user-images.githubusercontent.com/51957264/204899576-86dc3f69-f986-4fa0-892d-4d2fedbd68e1.png)
same error

**Comment by Yikesec** [comment]
> to download package undefined
> ❌ Cannot read property 'hasOwnProperty

because you need to delete its appdata 

go into explorer's url bar and type %appdata% then delete anything that has the word discord in it
go back a folder and open roaming and do the same

**Comment by zerebos** [comment]
This has been fixed
