### ISSUE TITLE
Suggestion: Enable/Disable All toggle for plugins

### ISSUE THREAD

**Issue by asorel1942** [BetterDiscord/Installer#23]
An option to enable or disable all plugins simultaneously would be very helpful for future updates.

**Comment by Tropix126** [comment]
This might be doable as something to integrate into the repair option.

**Comment by rauenzi** [comment]
> An option to enable or disable all plugins simultaneously would be very helpful for future updates.

Do you mean an option in the client? Like in the plugin list?

**Comment by asorel1942** [comment]
> > An option to enable or disable all plugins simultaneously would be very helpful for future updates.
> 
> Do you mean an option in the client? Like in the plugin list?

Yes.

**Comment by zerebos** [comment]
Ah then this is something for https://github.com/rauenzi/BetterDiscordApp and has already been suggested there
