### ISSUE TITLE
Install from script

### ISSUE THREAD

**Issue by godalming123** [BetterDiscord/Installer#230]
**Is your feature request related to a problem? Please describe.**
I have a script to setup and install my linux system would there be a way to skip the gui and just use a cli interface with the better discord installer.

**Describe the solution you'd like**
I would like an sh file or appimage (if they can provide a cli interface) that can be downloaded, added executable permissions and ran from the terminal using a terminal interface instead of a gui to install.

**Describe alternatives you've considered**
You could also add a script that has options such as
```
bash install-better-discord.sh install-location=/blah/blah
```

**Comment by dav1312** [comment]
Try using https://github.com/bb010g/betterdiscordctl

**Comment by zerebos** [comment]
A separate CLI is in the works, but it will not be a part of this installer
