### ISSUE TITLE
Im not sure if this is the same person running the webstore version but...

### ISSUE THREAD

**Issue by ghost** [BetterDiscord/Installer#237]
Whenever i try to use the webstore version, it keeps telling me to install the latest version and brings me here but since i only have chrome os, i cant use the linux version so i was wondering if you could fix the web version and update it and if the webstore version is fake maybe make one

thanks

**Comment by zerebos** [comment]
There is no official web version, anything you are using for chrome or chrome os is unofficial. I do not intend to make one.

**Comment by dav1312** [comment]
### You should uninstall that as soon as possible.

The extension that is currently in chrome's web store is a modified version of BdBrowser that will probably steal your Discord account at any moment.
