### ISSUE TITLE
Have an Option to disable BetterDiscord for/until the user restarts Discord or some time limit like One Day or an Hour

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [BetterDiscord/Installer#239]
**Is your feature request related to a problem? Please describe.**
I am requesting this feature because sometimes discord is very slow at sending messages and files and/or receiving them. And also the fact that I am not using BetterDiscord to some of my friends because they are a little too obedient to Discord's TOS.

**Describe the solution you'd like**
In the settings part of BetterDiscord, I would like a "Disable BD for: `Choice`". The `Choice` could be: 
- 1 Hour
- 5 Hour
- 1 Day
- Until I restart Discord
- Until I turn it back on

**Describe alternatives you've considered**
Another "Alternate" I have thought of is to have a pop-up everytime you start discord (it may be annoying), asking whether to start discord or not, and have like a check mark saying "Don't ask me again (Go to Settings to Enable/Disable it". 

**Additional context**
I have made a representation of what it may look like (Sorry if it doesn't look good I used MS Paint and I am not good at editing pictures)
![image_2022-02-06_221406](https://user-images.githubusercontent.com/74773615/152695086-970cc816-00b3-4a86-b354-9432de982644.png)

P.S.
I can understand if you reject this Feature Request as the Devs have other work to do.

**Comment by dav1312** [comment]
This is the installer repository, this should be in https://github.com/BetterDiscord/BetterDiscord

**Comment by Ujjwal-Rohilla** [comment]
What do you mean? I am confused. Am I supposed to put this Suggesting in the Installer Repository, if yes, I am unable to find a place to put it.

**Comment by dav1312** [comment]
No, I'm telling you that this is the installer repository.
This suggestion should be here: https://github.com/BetterDiscord/BetterDiscord

**Comment by Ujjwal-Rohilla** [comment]
I have made a new issue in the 'BetterDiscord' one.
https://github.com/BetterDiscord/BetterDiscord/issues/1201#issue-1125637057
