### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(439)

### ISSUE THREAD

**Issue by IagoFloriano** [BetterDiscord/Installer#242]
**Describe the bug**
When trying to open the installer it fails, command line output shows error FATAL:gpu_data_manager_impl_private.cc(439)

**To Reproduce**
Open installer through appimage or from running yarn install; yarn dev on coloned repo

**Expected behavior**
Installer open

**Outputs**
Output of yarn dev command: https://pastebin.com/89KNrmxg
Output from running the appimage:
[11848:0215/212530.102111:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  BetterDiscord-Linux.AppImage

**System Information:**
 - OS: Arch linux, kernel 5.16.9-arch1-1
- Discord Version: Stable 115008 (97968e1) Host 0.0.16

**Comment by SelfMadeSystem** [comment]
You can add the `--disable-gpu-sandbox` flag and it'll work.

**Comment by IagoFloriano** [comment]
Thanks, the installer now opens and Im able to use it, however the installer is not being able to install it properly. I click install (with discord closed) and when i open discord after installing it is vanilla discord. The only output the installer gives in a terminal is when i click the checkbox to agree to licence agreement, the output is: `(betterdiscord-installer:57664): GLib-GIO-CRITICAL **: 22:55:54.451: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed` which i dont think is related to the actual installation process.
EDIT: If i should open a new issue for this just let me know and ill do it.

**Comment by IagoFloriano** [comment]
I updated my system this morning and reinstalled better discord and now it worked, dont know what made a difference. Here is the pacman log for this update if it helps with anything (If the time is somehow important this was on UTC -3). https://pastebin.com/pf0m1h96
