### ISSUE TITLE
New installer stuck on "Attempting to kill Discord"

### ISSUE THREAD

**Issue by Velcorn** [BetterDiscord/Installer#25]
When I try to install BD using the newest installer beta, it just hangs at the above message and never continues.

**Comment by Tropix126** [comment]
Try killing discord manually (through the system tray). What happens then?

**Comment by ItsMartin030** [comment]
Open Task Manager and kill every process with the name "Discord.exe" like shown below.
![image](https://user-images.githubusercontent.com/57033944/113365480-b2226080-9356-11eb-8d89-fd7f8fa285f9.png)
Then try to install it again.

**Comment by L-m-b** [comment]
If trops & martins suggestions don't work, delete your `%localappdata%\discord\app-0.0.309\resources\app` folder and attempt a reinstall.
may be old files screwing with it.

**Comment by Velcorn** [comment]
Thanks for your suggestions, but unfortunately that didn't help. Tried reinstalling Discord, too, to no avail. I'll try messing around with a bit a bit more in the meantime.

**Comment by Velcorn** [comment]
I manually installed it with no issues. I'll leave this open if someone discovers a solution for the installer so people with the same issue might see the solution. Otherwise it can be manually closed.

**Comment by Cosmiiko** [comment]
Same issue. No Discord process running, yet the installer still attempts to kill one.
Have tried reinstalling Discord but to no avail.

![Screenshot_5](https://user-images.githubusercontent.com/29412451/113477828-03307280-9485-11eb-9640-dbba9fc23a5f.png)

**Comment by Velcorn** [comment]
Ahh, wild. That's most certainly it, because I recently installed Kite, which made me put System32 in path, but I had to uninstall because it crashed Cold War, so I removed System32 from path again. Thanks for the solution. Will close this issue once I'm back at my PC and can verify, but I'm sure that's the problem.

**Comment by L-m-b** [comment]
Funny thing, when I ran the installer initially, it didn't close discord, maybe due to me manually installing the beta 2 days before the installer became available to use, but nonetheless I find I interesting

**Comment by OsamaKhlefawi** [comment]
i have system32 in my path and i still have the problem idk why

**Comment by wheelz-if** [comment]
can someone pls explain how to do it in basic language :C 
mine's stuck in killing discord and dk what to do

**Comment by OsamaKhlefawi** [comment]
same I dont understand the code stuff but its stuck for me

**Comment by acemint** [comment]
Yes that also does work in my case and I'm gonna rephrase the answer above.
1. Go search "path" in windows search bar.
2. Press "environment variables"
3. Go to system variables
4. Choose PATH variable, double click it
5. Press new and then add C:\Windows\System32
6. Press ok
Hope it helps

**Comment by OsamaKhlefawi** [comment]
installing it now works but the repair now gives me a different message 

![image](https://user-images.githubusercontent.com/50362412/120225867-b5e73c00-c24e-11eb-990d-d73368d756df.png)
![image](https://user-images.githubusercontent.com/50362412/120225900-c7304880-c24e-11eb-81e1-bcfd315d97ff.png)

**Comment by 57382** [comment]
+1

**Comment by Anomino-dev** [comment]
Well I see that this is happening to so many people, So Maybe The new beta setup has a bug which stops execution on killing discord

**Comment by L-m-b** [comment]
> Well I see that this is happening to so many people, So Maybe The new beta setup has a bug which stops execution on killing discord

i recall this issue is due to old installation files and broken files as part of discord itself causing it to halt the installation, if you delete the 'discord/{version}' folders from %appdata% and %localappdata% and reinstall discord itself and make sure to run the bd installer as admin, it should have no issue.

This issue thread was made due to a broken installer back in 2021, it has long since been fixed and is not of concern at this moment.

**Comment by NyStarfire** [comment]
I have fixed the issue with the crash at the install of Better Discord where it freezes at the part: Restarting Discord Attempting to kill Discord.
The solution wasn't that complicated, but for a person who isn't very adept at computers, it could be complicated as heck. But I don't let circumstances tell me "NO". Here is my fix:

Discord is auto installed in this path;
C:\Users\(user name here)\AppData\Local
i.e. C:\Users\Jane Doe\AppData\Local

What I did was went to this exact location from This PC Local Disk (C:)
and transferred the entire Discord folder from C:\Users\Jane Doe\AppData\Local to:
C:\Windows\System32
Then I ran the Better Discord as Administrator
File Missing. Darn But, I don't let things tell me "NO". So, I returned the Discord to its Original file location. Again, I ran as Administrator, 
Bang!!!! it finished installing.
I don't know what moving the Discord Folder to System32 did, but, What it did do when I returned it to its original location, was fix the issue at hand.

**Comment by priyansh1471** [comment]
> 

not worked for  me.

**Comment by L-m-b** [comment]
> I have fixed the issue with the crash at the install of Better Discord where it freezes at the part: Restarting Discord Attempting to kill Discord. The solution wasn't that complicated, but for a person who isn't very adept at computers, it could be complicated as heck. But I don't let circumstances tell me "NO". Here is my fix:
> 
> Discord is auto installed in this path; C:\Users(user name here)\AppData\Local i.e. C:\Users\Jane Doe\AppData\Local
> 
> What I did was went to this exact location from This PC Local Disk (C:) and transferred the entire Discord folder from C:\Users\Jane Doe\AppData\Local to: C:\Windows\System32 Then I ran the Better Discord as Administrator File Missing. Darn But, I don't let things tell me "NO". So, I returned the Discord to its Original file location. Again, I ran as Administrator, Bang!!!! it finished installing. I don't know what moving the Discord Folder to System32 did, but, What it did do when I returned it to its original location, was fix the issue at hand.

don't do this. this is stupid.
just delete the entire discord folder then fresh install if you have this issue.

Also stop necroing this issue its already dead.
