### ISSUE TITLE
BetterDiscordX extension not up to date.

### ISSUE THREAD

**Issue by NopeProsOnly** [BetterDiscord/Installer#250]
Please update the extention

**Comment by dav1312** [comment]
You should uninstall that extension as soon as possible, it's not official and the guy that made it already tried multiple times to steal people's accounts using it

**Comment by tropicaaal** [comment]
@kaden-tech Uninstall that extension immediately and reset your discord account password as soon as possible. Any browser extension claiming to be BetterDiscord or affiliated with BetterDiscord is likely either malicious or a cryptocurrency miner.
