### ISSUE TITLE
Beter discord mobile 

### ISSUE THREAD

**Issue by TYHAKEN** [BetterDiscord/Installer#253]
Beter discord mobile beter discord na telefon to by była dobra opcja ponieważ nakladki i to wszystko  tła możliwośći nadane dzięki beter discordowi nie ograniczajmy tego do tylko konpoterow

**Comment by QbDesu** [comment]
See https://betterdiscord.app/FAQ question 5. Also don't expect people to reply to issues opened in languages other than the project's language.
