### ISSUE TITLE
Add installer switches

### ISSUE THREAD

**Issue by solomoncyj** [BetterDiscord/Installer#254]
**Is your feature request related to a problem? Please describe.**

 switches in EXE installer
**Describe the feature you'd like**

switches that allow silent execution of exe
eg.
``` 
1.<path> /S : automaticaly installs better discord to all found versions of discord
2.<path>/uninstall : uninstalls better discord to all found versions of discord
3. <path> [/uninstall] /target <target version> : installs/uninstalls better discord to target version only
note : [] means optional
```
**Additional context**

**Comment by solomoncyj** [comment]
boink

**Comment by solomoncyj** [comment]
Any updates

**Comment by Technetium1** [comment]
See https://github.com/BetterDiscord/BetterDiscord/issues/1215 & https://github.com/BetterDiscord/BetterDiscord/issues/382 for why this will likely not happen.
