### ISSUE TITLE
Where does BetterDiscord find the discord application?

### ISSUE THREAD

**Issue by popQA17** [BetterDiscord/Installer#257]
I'm tryna install BetterDiscord on ZorinOS 16 (Or debian basically), and managed to install discord on flatpack and snapstore. However, no matter what I do to browse for Discord, BetterDiscord seems to be unable to find it. 

I just need to know how and where does BetterDiscord search for well Discord. Thanks!

**Comment by SmolAlli** [comment]
You might have more luck with [betterdiscordctl](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172)

**Comment by Technetium1** [comment]
> You might have more luck with [betterdiscordctl](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172)

This is absolutely the correct answer.
