### ISSUE TITLE
Very annoying bug 

### ISSUE THREAD

**Issue by smallsnailhehe** [BetterDiscord/Installer#258]
Hello there! I am a moderator of the witch's tavern discord server and we have a few channels that are hidden to only be seen by moderators and administrators, but members with BetterDiscord, such as one of our formed mods, can see private channels. They cannot type or enter them, but they know they exist, which is not good. 

Even when muted (meaning they dont have any permissions to see any channels except for the rules and the mute chat), they can still see all the channels. We have a bot developer on our team and a bunch of smart people that have been using discord and making sophisticated servers for years now, and we are assured that theres no problem within our server making this happen. Again, its only the members using BetterDiscord that have this problem.

If possible, please fix this bug. It gets very annoying.

(the picture is of what they see and a few of the channels here shouldnt be visible)
![IMG_0824](https://user-images.githubusercontent.com/101992994/159178428-0a21f70a-3480-427f-9a66-229767a7f19a.png)

We sadly dont know what device they use.

Best of luck and kind regards, 
El

**Comment by dav1312** [comment]
This is not an issue with the installer, this is just how Discord's api works, blame Discord

**Comment by smallsnailhehe** [comment]
Ah, thank you so much for your response! We will figure out another solution to this :)
