### ISSUE TITLE
Warn instead of Fail when Self-Signed Certificates are Detected

### ISSUE THREAD

**Issue by aaronliu0130** [BetterDiscord/Installer#262]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the self-signed cert I use in conjunction with my reverse proxy that allows me to get GitHub faster makes the BDInstaller fail.

**Describe the solution you'd like**
Don't make self-signed certs fail the installer and instead instigate a warning that tells that you have a self-signed cert and that you should probably not continue unless you know what you're doing. Make two buttons "continue" and "back" and default to back.

**Describe alternatives you've considered**
Disable my reverse proxy. This gives me a high chance of not being able to download the file from Github in time or even failing the API check.

**Comment by QbDesu** [comment]
most definite no on that, that defeats the purpose of TLS which is E2E encryption the hosts. especially for most not so tech-savvy users who would just click away the warning as long as it let's them install the app.

If it doesn't detect your system's installed certificates you can try using `--ignore-certificate-errors`, but that maybe doesn't affect requests done using node's APIs (which we use)

**Comment by aaronliu0130** [comment]
Oh, ok!
