### ISSUE TITLE
Add installer to winget-pkgs

### ISSUE THREAD

**Issue by PAI5REECHO** [BetterDiscord/Installer#263]
**Is your feature request related to a problem? Please describe.**
It'd be nice to non-interactively install the BetterDiscord installer from the terminal in Windows (`winget install BetterDiscord`)

**Describe the solution you'd like**
Package the installer as an MSI for Windows so it may be added to [`winget-pkgs`](https://github.com/microsoft/winget-pkgs)

**Describe alternatives you've considered**
Never being able to ever automate installation :(

**Comment by Technetium1** [comment]
Here are the related issues and the reasons this probably will not happen anytime soon:
https://github.com/BetterDiscord/BetterDiscord/issues/1252#issuecomment-1107358452
https://github.com/BetterDiscord/BetterDiscord/issues/382
https://github.com/BetterDiscord/BetterDiscord/issues/1215

**Comment by PAI5REECHO** [comment]
This project could easily use https://github.com/electron-userland/electron-installer-windows to create a Windows installer

**Comment by QbDesu** [comment]
that completely misses the point of the installer, having to install the installer first is just nonesense, the installer is portable for a reason.

**Comment by PAI5REECHO** [comment]
It isn't mutually exclusive, programs can provide both a system installer and portable app. Using a package manager is an objectively superior way to install software, it reduces wasted time when you setup a new computer since you can simply import a list of the packages/apps you previously had installed.

**Comment by SmolAlli** [comment]
how can a client modification be a portable app.

**Comment by virtualex-itv** [comment]
Chocolatey makes this possible...
[betterdiscord](https://community.chocolatey.org/packages/betterdiscord)

**Comment by zerebos** [comment]
Sorry we don't wish to make this into a windows installer at this time. We'd rather have package managers use our CLI once it releases to the public. CLI installs with electron don't make much sense imo

**Comment by zerebos** [comment]
@virtualex-itv I appreciate you making a chocolatey package for this, I could not figure it out myself. Would you be willing to help out when the CLI releases?

**Comment by virtualex-itv** [comment]
> @virtualex-itv I appreciate you making a chocolatey package for this, I could not figure it out myself. Would you be willing to help out when the CLI releases?

@rauenzi - I'd be happy to help.  the chocolatey package leverages a tool called AutoHotkey to handle the silent installation steps from the GUI automagically since there is no native silent install parameter.

When can we expect a 1.21 or 1.3 of this installer as 1.2 is plagued by the "black screen" bug which then impacts the installation via chocolatey?  It seems to work fine on my machine but on a few others, including test VMs, they are experiencing the black screen bug.

**Comment by zerebos** [comment]
Yeah I saw your use of AHK in the choco package you published, was interesting to look through. The next version will probably be within the next couple of days. Feel free to reach out on Discord if you want more info, we've gotten a bit off topic here
