### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by Crylia** [BetterDiscord/Installer#265]
Describe the Bug
Trying to launch the Appimage results in the following error
[13824:0512/204157.656581:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

To Reproduce
Download the Appimage from the website and launch it

Expected Behavior
For it to launch

Additional Context
I got an RTX 3070
NVIDIA-SMI 510.68.02 Driver Version: 510.68.02 CUDA Version: 11.6

System Information:
 - OS: Linux Pop!_OS 22.04

**Comment by ghost** [comment]
run --disable-gpu-sandbox with ./BetterDiscord-Linux.AppImage --disable-gpu-sandbox or https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by SmolAlli** [comment]
Duplicate of #247. When you were told to go to the right repository, maybe you should have read through the opened issues before just reposting.
