### ISSUE TITLE
Disable Restart On Crash

### ISSUE THREAD

**Issue by Kinomora** [BetterDiscord/Installer#267]
**Is your feature request related to a problem? Please describe.**
When BD crashes either because of itself or a plugin entering an unrecoverable state, the app crashes, a pop-up that says "BetterDiscord has crashed, please check your plugins an restart discord" and then it automatically lauches "vanilla" discord.

**Describe the solution you'd like**
An option in the settings menu to disable automatic restarting or block "vanilla" discord from launching so I can just re-start BD manually.

**Describe alternatives you've considered**
The only alternative is the vanilla client and, god, please no.

**Additional context**
I would provide a screenshot/video if I could but it's not exactly predictable for the app to crash

**Comment by SmolAlli** [comment]
This doesn't seem like the right place for this issue.
