### ISSUE TITLE
Can´t click on selecting menu in plugins settings

### ISSUE THREAD

**Issue by phiko-misc** [BetterDiscord/Installer#274]
**Describe the bug**
I can´t click on selecting menu in plugins settings

**To Reproduce**
1. Click on  'User Settings'
2. Scroll down to 'Plugins'
3. Click on 'Plugins'
4. Click on 'The plugins settings'
5. Click on \/ in 'plugins settings

**Screenshots**
https://user-images.githubusercontent.com/18640250/177523455-51259bb7-ed0c-4bd8-ac9a-a5d16f228643.mp4

**System Information:**
 - OS: Windows 10
- Discord Version: Canary

**Comment by SmolAlli** [comment]
This repository is for the installer for BD, not for anything relating to the way BD works in Discord. Please make a post in https://github.com/BetterDiscord/BetterDiscord (and give a link for screenshots/videos that work)
