### ISSUE TITLE
Update don't work

### ISSUE THREAD

**Issue by Mimexe** [BetterDiscord/Installer#28]
**Describe the bug**
The update don't work i clicked and discord shutdown and nothing is updatated 

**To Reproduce**
2. Click on Update Now

**Expected behavior**
The update don't work i clicked and discord shutdown (no restart) and nothing is updatated 

**Screenshots**
![2021-04-02_19h31_54](https://user-images.githubusercontent.com/74558118/113439066-16423480-93ea-11eb-99e5-22ce1067272d.png)

**System Information:**
 - OS: Windows
- Discord Version: Stable

**Additional context**
None

**Comment by Tropix126** [comment]
This is not an issue with the installer, but rather an issue of the self-updater in the non-beta client. Grab the latest version of the installer from below and run the install option.
| [Windows (7+)](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Windows.exe)  | [macOS (10.10+)](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Mac.zip) | [Linux](https://github.com/BetterDiscord/Installer/releases/latest/download/BetterDiscord-Linux.AppImage) |
| ------------- | ------------- | ------------- |
