### ISSUE TITLE
БWill the add-on be added to the phone discord? 

### ISSUE THREAD

**Issue by Dai56764** [BetterDiscord/Installer#283]
Hello I wanted to ask if there will be permission for plugins and themes on Phone Discort? 

( For example, on Android or iPhone). 

This feature will be used for a very long time and your resolution will soar into space from the downloads.

**Comment by Technetium1** [comment]
No mobile version.

**Comment by Inve1951** [comment]
BD is for the electron version only - not compatible with anything else.
