### ISSUE TITLE
BetterDiscord

### ISSUE THREAD

**Issue by aggressivemidget** [BetterDiscord/Installer#286]
when i got in my discord settings after everything is installed when i got to the better discord settings nor my themes or plugins options is there so i can add plugins or anything its like normal discord

**Comment by 1orel** [comment]
i got that same issue too its just like a normal discord and i cant see my plugins or theme options

**Comment by StarWolf3000** [comment]
BetterDiscord/BetterDiscord#1404

**Comment by realguystuff** [comment]
this usually happens when u install canary or ptb. try using stable, it happened to me too
