### ISSUE TITLE
Wrong .desktop location on linux

### ISSUE THREAD

**Issue by Soggy-Pancake** [BetterDiscord/Installer#288]
Betterdiscord changed the .desktop file to /usr/share/discord/Discord while discord was installed in /opt/discord

Run installer
Install normally

Expected: Desktop/start menu links work

![image](https://user-images.githubusercontent.com/54160598/197924620-c94a2046-e3c6-41ca-99ff-fda1999ec9d2.png)

![image](https://user-images.githubusercontent.com/54160598/197924694-5eb5e622-15f1-45ab-8de4-13da20d8cd24.png)

 - OS: Manjaro
- Discord Version: Stable

**Comment by Inve1951** [comment]
The BD installer does not mess with discord's desktop integration.
What makes you think BD caused this?

**Comment by Soggy-Pancake** [comment]
The desktop shortcut worked before installing betterdiscord. The .desktop shortcut that was messed with was /opt/discord/discord.desktop

**Comment by QbDesu** [comment]
That doesn't change the fact that the installer doesn't touch these things. It doesn't even touch the stuff in `/opt/` or `/usr/share` but only patches a single file in the `~/.config/discord` and installs its own files in `~/.config/BetterDiscord`. It doesn't create any `.desktop` files, it doesn't modify any `.desktop` files. Not to mention that a desktop file in `/opt/discord` wouldn't even be considered by any application unless its symlinked to `/usr/share/applications` or another appropriate path.

What is more likely is that Manjaro didn't update the desktop file when the discord package changed its installation directory.

**Comment by Inve1951** [comment]
Note that the installer (by default) runs without root privileges so it in fact cannot change files in /opt or /usr.
