### ISSUE TITLE
BetterDiscord not showing in the files

### ISSUE THREAD

**Issue by MiteBeParker** [BetterDiscord/Installer#296]
Better discord says its installed but will not show up in the files or in the setting of discord yes i have made sure to see if there going to the right spot and they are wondering if there is a way to fix it i am using the most recent windows 11 update and i am using discord canary

**Comment by Adaptz** [comment]
Using PBT, windows 10, the newest installer, and am having the same issue, I'm unable to use the software no matter how many times I uninstall and reinstall.
