### ISSUE TITLE
Betterdiscord not launching

### ISSUE THREAD

**Issue by ArchbishopTCO** [BetterDiscord/Installer#300]
When I booted up discord today on pc it didn't launch better discord, or any of my themes. My themes tab is also not showing. I tried repairing better discord, but it didn't work. I tried uninstalling and reinstalling, but it didn't work. This happens every once in a while repeatedly, any ideas on how to fix this?

**Comment by WolfKann** [comment]
Same

**Comment by SupraM4** [comment]
moi sur discord je n'est pas la barre better discord et je ne peut pas télécharger la nouvelle MAJ avez vous des réponse pour moi ?
