### ISSUE TITLE
themes not showing on mac

### ISSUE THREAD

**Issue by candynikos** [BetterDiscord/Installer#301]
i downloaded new better discord, my friend did too with a different laptop than mine and has no issues
this is what shows up instead if the themes. 
<img width="210" alt="Screenshot 2022-12-12 at 7 18 52 PM" src="https://user-images.githubusercontent.com/120429454/207194149-b270f22b-3a51-47d8-905a-afec19f7c633.png">

**Comment by pamcicles** [comment]
mine is doing the same :'(
