### ISSUE TITLE
Windows won't allow 1.2.0 to run

### ISSUE THREAD

**Issue by bigbruh7429** [BetterDiscord/Installer#302]
When I try to launch the new version, windows prevents it from opening.

**Comment by zerebos** [comment]
Can you elaborate? Do you mean smartscreen? Please use issue templates!

**Comment by Pharaoh2k** [comment]
@rauenzi For me it just doesn't do anything when I am trying to launch it on windows 11 x64. No smartscreen, nothing.
Previous version launches fine, but doesn't fix better discord after I complete the fix. I launch Discord and it's just the default.

**Comment by Pharaoh2k** [comment]
And I did try re-downloading the exe several times, btw.

**Comment by Cassanderx** [comment]
For me, running the latest version of the installer resulted in a smart screen popup. Allowing it to run anyway simply resulted in the background panel appearing but never loading any of the other controls.

Here's what I mean:
![image](https://user-images.githubusercontent.com/62576705/207218462-b6089d5d-a94b-4421-9e8f-643b58cc13ae.png)

Launching as admin as well as force closing and reopening yielded no results. Running through command line provided no error messages. 

Older installer still works fine

**Comment by zerebos** [comment]
Please try the version here on my personal server https://zerebos.com/BetterDiscord-Windows.exe

**Comment by Cassanderx** [comment]
> Please try the version here on my personal server https://zerebos.com/BetterDiscord-Windows.exe

This version of the installer worked perfectly!

**Comment by Blunkie** [comment]
mine just doesnt load bd after i installed it regular discord opens with no bd load symbol etc

**Comment by Pharaoh2k** [comment]
> Please try the version here on my personal server https://zerebos.com/BetterDiscord-Windows.exe

I get the same exact result as downloading the exe from https://betterdiscord.app/ and from github.
It doesn't launch at all. Very weird. Never had any issue with better discord executables.

**Comment by zerebos** [comment]
The fix for this has been merged and will be fixed in next release.

**Comment by zerebos** [comment]
This is also a duplicate of #244
