### ISSUE TITLE
Windows blocking BetterDiscord

### ISSUE THREAD

**Issue by zeffdakilla** [BetterDiscord/Installer#303]
Since the new update, when I open BetterDiscord I get this.
![image](https://user-images.githubusercontent.com/111836537/207226502-22dbcca0-85da-4c8e-aa3e-a5787308cb8b.png)
I can still run the file anyway, but I thought I'd report this.

**Comment by maenDisease** [comment]
It's because it's a new installer that Windows hasn't recognized as known yet.

**Comment by ghost** [comment]
This is pretty common with new files and exes. Just click more info and then run anyway

**Comment by ruinn139** [comment]
i clciccked more info and it doesnt have run anyway idk why

**Comment by Technetium1** [comment]
Right click -> properties -> general -> check Unblock -> Apply
