### ISSUE TITLE
Discord crash when right clicking

### ISSUE THREAD

**Issue by Koroshibi** [BetterDiscord/Installer#304]
Hello,

**Bug description**
Crash discord when right clicking on any message

**To Reproduce**
1. Go to 'DM or server'
2. Right Click
3. See error

**Expected behavior**
See the normal drop menu instead of having a crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/64699871/207288973-d24edb68-d29e-4954-ae9a-ab3f24f4c938.png)

**System Information:**
Stable 163658 (28d41b4) 
Host 1.0.9008 (27798) 
Windows 11 64-Bit
Better Discord : Core v1.8.3

**Comment by Ihavenolif** [comment]
Are you using the BetterVolume plugin? I've had this issue as well and disabling this plugin solved it for me.

**Comment by Koroshibi** [comment]
> Are you using the BetterVolume plugin? I've had this issue as well and disabling this plugin solved it for me.

just find out it's because of MsgLoggerV2
