### ISSUE TITLE
Discord crashes when right clicking a message.

### ISSUE THREAD

**Issue by BjarneVDB-1952100** [BetterDiscord/Installer#305]
**Describe the bug**
When trying to right-click a message, the client crashes and shows the "Oof, crashed. Click here to reload" screen.

**Expected behavior**
Can no longer right click a message to reply.
![image](https://user-images.githubusercontent.com/73596571/207321211-5fa1b125-3e13-442f-8a74-75a3456b7273.png)

**System Information:**
Stable 163658 (28d41b4)
 Host 1.0.9008 (27798)
 Windows 10 64-Bit (10.0.22621)

**Comment by NicciZar** [comment]
Works fine for me

Stable 163658 (28d41b4) 
Host 1.0.9008 (27798) 
Windows 10 64-Bit (10.0.19045)

**Comment by Anonymous2321** [comment]
Not sure but are you using MessageLogger for me i stopped it and now it works fine for me

**Comment by Technetium1** [comment]
Disable `BDContextMenu` and `BetterVolume` if you have them.

**Comment by BjarneVDB-1952100** [comment]
Issue was fixed with the new update. 
Cause was probably a mix of BetterDiscord and MessageLoggerV2 not working well together
