### ISSUE TITLE
New update makes it so the program cannot find any discord versions

### ISSUE THREAD

**Issue by WolfKann** [BetterDiscord/Installer#306]
As the title implies, even selecting the folder and launching the discord program inside the folder doesn't work.

![image](https://user-images.githubusercontent.com/17802255/207327825-1c462ad9-1fbd-4ec6-abf3-153999bec291.png)

![image](https://user-images.githubusercontent.com/17802255/207327850-80021f8c-9c09-4f62-9ab9-a2bd6c1bb91e.png)

**Comment by zerebos** [comment]
Check your modules folder for the contents

**Comment by 3nt3** [comment]
I'm experiencing the same problem

**Comment by tvs-edge** [comment]
me2

**Comment by deviantsemicolon** [comment]
I'm experiencing this problem on Linux. I can't find the version anywhere

**Comment by yegetables** [comment]
> Check your modules folder for the contents检查您的模块文件夹的内容
![image](https://user-images.githubusercontent.com/37119488/226273735-1b808adc-d01f-4bc5-97b0-7bd87c196777.png)

i don't know how to deal it.

**Comment by okayscylla** [comment]
Not working for me either :(

**Comment by dopadream** [comment]
Doesn't work for me either. I'm not able to set it manually.

**Comment by zerebos** [comment]
For those that think they are experiencing this issue, please join our Discord for support. Just saying that it doesn't work is not nearly enough information for us to debug it.

**Comment by dopadream** [comment]
> For those that think they are experiencing this issue, please join our Discord for support. Just saying that it doesn't work is not nearly enough information for us to debug it.

For the record, manually compiling the latest build fixed it for me. I don't think that's necessary.

**Comment by ochen1** [comment]
Manually building master did not work for me.

**Comment by skunkmommy** [comment]
Bump, I have this exact issue except telling it to use modules folder does absolutely nothing.
1.3.0 installer, on Windows 10.
Doesn't matter if I run as admin or not.

**Comment by Inve1951** [comment]
> For those that think they are experiencing this issue, please join our Discord for support. Just saying that it doesn't work is not nearly enough information for us to debug it.

bump ^

> Bump, I have this exact issue except telling it to use modules folder does absolutely nothing.
1.3.0 installer, on Windows 10.
Doesn't matter if I run as admin or not.

What's the installer output? Also, do NOT run it as admin. That just screws with the file permissions leading to more trouble.

**Comment by skunkmommy** [comment]
> > For those that think they are experiencing this issue, please join our Discord for support. Just saying that it doesn't work is not nearly enough information for us to debug it.
> 
> bump ^
> 
> > Bump, I have this exact issue except telling it to use modules folder does absolutely nothing.
> > 1.3.0 installer, on Windows 10.
> > Doesn't matter if I run as admin or not.
> 
> What's the installer output? Also, do NOT run it as admin. That just screws with the file permissions leading to more trouble.

I can't get the output because my issue happens before you'd normally see the output.
I can't even start the installation process. Whether or not I run as admin it doesn't matter.
I doubt it's a path-related issue: but just in case, my user folder is named `spudpiggy` (as in, %appdata% points to `C:\Users\spudpiggy\AppData\Roaming` on this user)

**Comment by zerebos** [comment]
Please join the discord if you want some more personalized support
