### ISSUE TITLE
Stuck on starting

### ISSUE THREAD

**Issue by MannuVilasara** [BetterDiscord/Installer#308]
when I click the setup it gets started but shows nothing
![image](https://user-images.githubusercontent.com/117009138/207527053-af9bbb47-eea3-4299-a043-0dfac3889a26.png)

**Comment by Zachtopia** [comment]
I'm having the exact same issue :(

**Comment by TesenDesk** [comment]
Same for me :(

**Comment by tnbhaeufi** [comment]
same for me. Radeon RDNA2 (6800)

**Comment by zerebos** [comment]
Duplicate of #302
