### ISSUE TITLE
[bug] discord crashes when i click right on seerver setting 

### ISSUE THREAD

**Issue by Iliatl7** [BetterDiscord/Installer#309]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by NicciZar** [comment]
Try to give more info.

Are you using any other plugins? What plugins are you using.

Also show version of discord etc (just as the template you didn't fill out asked you for)
