### ISSUE TITLE
Gift and GIF button removal doesn't work

### ISSUE THREAD

**Issue by ensorcell** [BetterDiscord/Installer#31]
**Describe the bug**
Gift and GIF picker buttons still appear in message box when options to hide them are enabled

**To Reproduce**
1. Enable "Hide Gift Button" or "Hide GIF Button" under the BetterDiscord settings
2. Check message box

**Expected behavior**
Gift and GIF picker buttons disappear from message box

**Screenshots**
[Settings](https://i.imgur.com/QFsDiJJ.png)
[Buttons still appear](https://i.imgur.com/RsLdcH1.png)

**System Information:**
 - OS: Windows 10
- Discord Version: Stable 81297

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/BetterDiscordApp/, however this is a known issue and will be fixed soon.
