### ISSUE TITLE
program stuck in "killing discord" [already tried the suggested methods]

### ISSUE THREAD

**Issue by superking816pro** [BetterDiscord/Installer#312]
**Describe the bug**
i was seeing the video on NTTS's ggsans to the old discord font and when i tried to install it it stuck on the killing discord page for hours.

**To Reproduce**
1. Go to 'the better discord installer'
2. Click on 'i agree the license and next'
3. Click on 'install better discord and next'
5. error:

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\ANANDHI\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\ANANDHI\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\ANANDHI\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\ANANDHI\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: C:\Users\ANANDHI\AppData\Local\Discord\app-1.0.9008\modules\discord_desktop_core-1\discord_desktop_core
✅ Injection successful
✅ Shims injected

Restarting Discord...
Attempting to kill Discord

**Expected behavior**
mentioned in the NTTS's channel

**Screenshots**
![Screenshot 2022-12-19 192654](https://user-images.githubusercontent.com/93249134/208441889-3291a0db-cf1f-43b9-b943-26283cb7712c.png)

**System Information:**
 - OS: Windows

**Comment by fowlis** [comment]
Make sure you have the latest version of the installer from the [releases page](https://github.com/BetterDiscord/Installer/releases)
Then in order, try:
1. Once the installer reaches "Attempting to kill Discord", 
  then `Alt` + `f4` on Discord
  then exit the installer
  and reopen Discord
2. Reinstall Discord following [this guide](https://support.discord.com/hc/en-us/articles/115004307527--Windows-Corrupt-Installation) then retry the installer
3. Try out a [manual install](https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation)

**Comment by superking816pro** [comment]
i have already done a reinstall of discord but thank you for taking your time to suggest this.

**Comment by superking816pro** [comment]
thanks the manual install worked, thank you for your time.
