### ISSUE TITLE
Uninstall with CLI

### ISSUE THREAD

**Issue by ShockedCoder** [BetterDiscord/Installer#314]
**Is your feature request related to a problem? Please describe.**
Since I can't use the installer, I used `pnpm inject` to install it instead.

**Describe the solution you'd like**
I'd like a `pnpm uninject`, so that I don't need to use the installer

**Describe alternatives you've considered**
I don't know how this works, and as such don't know what or how it installs it, so I don't know of any other way to uninstall this.

**Comment by maenDisease** [comment]
In the meantime, have you tried reinstalling Discord, and why can't you use the installer

**Comment by ShockedCoder** [comment]
The installer is just black and doesn't respond to anything

**Comment by zerebos** [comment]
A separate CLI is in the work, using electron for a cli is not ideal
