### ISSUE TITLE
Discord+ Wont Load

### ISSUE THREAD

**Issue by MidnightTheFabulous** [BetterDiscord/Installer#317]
I keep attempting to use Discord+, a theme on BetterDiscord to allow customization to things such as the background, home icon, UI font, and so on.

When loading up Discord on Windows, BetterDiscord does not load Discord+. It is enabled, there is accurate information in Discord+, and I have already tried uninstalling and reinstalling Discord+. I just updated Better Discord to its newest version. I am currently using Windows 10, not Windows 11. 

Below should be a screenshot of Discord+ being activated, but not running.

<img width="960" alt="Screenshot 2023-02-16 163722" src="https://user-images.githubusercontent.com/125618682/219519944-b4d6668b-1c0f-4007-bece-b97b4c33d18e.png">

**Comment by ghost** [comment]
This repository and issues is not for themes or theme issues. If you have an issue Join the [Discord ](https://discord.gg/0Tmfo5ZbORCRqbAd ) and make a support post.
