### ISSUE TITLE
Better Discord crash when i go to the options

### ISSUE THREAD

**Issue by CrashRider2002** [BetterDiscord/Installer#318]
what is the best way to start discord already completely reinstalled like better discord actually no more plugins in there crash but still if I want no idea what I can do in the options

**Comment by Momo1352** [comment]
Had the same issue, had to delete my betterdiscord folder (C:\Users\Momo\AppData\Roaming\BetterDiscord).
Maybe save ur BD folder before, when reinstalling BD ur Plugins are all Disabled.

 Also delete full discord Folder (C:\Users\Momo\AppData\Local\Discord).
 Then install discord fully new and reinstall BD.
 U can enable plugin after plugin if its an Plugins issue, to find out which Plugin.

**Comment by CrashRider2002** [comment]
didn't work even though there are no plugins in it and stuff like that

**Comment by CrashRider2002** [comment]
but if I delete BD in the BD installer and then reinstall it, it feels like it only works for one day

**Comment by Technetium1** [comment]
1. Discord Settings -> BetterDiscord Settings -> Enable DevTools & Enable Debug Logs
2. `CTRL+SHIFT+I` -> Console tab -> Default levels -> check the bottom 4
3. Look for red stuff around crash time
4. Check debug.log in your BD folder when it crashes
5. Don't upload long logs here, just the important snippets of errors
6. Turn off debug logging when you're done!

**Comment by Irowithinstars** [comment]
That won't do. I have the same problem and I crash immediatly after clicking on the settings icon. So I can't enable the devtools or debug logs like that.

**Comment by DorianDescamps** [comment]
Same issue here, when click on the settings logo without any plugin active, discord crash, i've tried uninstall, repair but same issue

**Comment by CrashRider2002** [comment]
it seems i fix it on the better discord dc is the key to solve it 

Feb 8, 2023
:BetterDiscord: Crashing when opening settings
Monitoring - Reload Discord until settings function correctly. This issue currently only affects Discord Stable.
If the issue persists:
Download this file https://cdn.discordapp.com/attachments/1072548654667284590/1075875719130914836/betterdiscord.asar
Press win+r and enter %appdata%/betterdiscord/data
Fully QUIT Discord (Alt+f4)
Move the file you downloaded to the folder you opened and replace the betterdiscord.asar

the link to the masage from better dc  discord
https://canary.discord.com/channels/86004744966914048/1031774670405501018/1031774670405501018

**Comment by Picadi0** [comment]
> it seems i fix it on the better discord dc is the key to solve it
> 
> Feb 8, 2023 :BetterDiscord: Crashing when opening settings Monitoring - Reload Discord until settings function correctly. This issue currently only affects Discord Stable. If the issue persists: Download this file https://cdn.discordapp.com/attachments/1072548654667284590/1075875719130914836/betterdiscord.asar Press win+r and enter %appdata%/betterdiscord/data Fully QUIT Discord (Alt+f4) Move the file you downloaded to the folder you opened and replace the betterdiscord.asar
> 
> the link to the masage from better dc discord https://canary.discord.com/channels/86004744966914048/1031774670405501018/1031774670405501018

not works still crashing when i try to open settings only when i delete better discord it's works but the goal is missing can't use better discord :/

**Comment by OnyXWolve** [comment]
same issue here did a complete wipe of all discord and better discord files yet it wont work same issue with crashing while going into settings and sadly now dont have my theme working

**Comment by Technetium1** [comment]
It's been posted about in the correct repo:
https://github.com/BetterDiscord/BetterDiscord/issues/1539#issuecomment-1447239025
You can get more information (and fixes) by [joining the Discord](https://discord.gg/0Tmfo5ZbORCRqbAd) and looking in the `Support` forum and `known-issues`.
