### ISSUE TITLE
Opening Installer

### ISSUE THREAD

**Issue by GQJIMU** [BetterDiscord/Installer#319]
When I open up the file of Better Discord it just doesn't do anything.

You open Better Discord for me to cause this.

**Comment by maenDisease** [comment]
Join the [BetterDiscord server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) and see this message https://canary.discord.com/channels/86004744966914048/1019697332910051430

**Comment by RianQuenlin** [comment]
How about "Post the message here" instead?

> Join the [BetterDiscord server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) and see this message https://canary.discord.com/channels/86004744966914048/1019697332910051430

**Comment by zerebos** [comment]
Duplicate of #302
