### ISSUE TITLE
Installer binary uses an absurd amount of storage space

### ISSUE THREAD

**Issue by Nexus24** [BetterDiscord/Installer#32]
Using the binaries from the release page, it comes out to be ~65MB of disk space for the (arguably basic) installer.
I'm thinking that you may have accidentally disabled some compiler optimizations or something when building the binary.
Something like this realistically should take way far less than 65 megabytes.

**Comment by Nexus24** [comment]
Turns out Electron packages Chromium with every binary. A shame, very bloated.

**Comment by FichteFoll** [comment]
On Linux, the build comes out to a whopping 180MB. I'd argue that is unacceptable for something that shows 3 different UI screens, one of which is a license dialog.

Is there interest in adding a CLI mode that can do without electron?

**Comment by FichteFoll** [comment]
betterdiscordctl has been updated and I just used it to reinstall BD successfully. 🚀
