### ISSUE TITLE
Theme backgrounds not working

### ISSUE THREAD

**Issue by MrFriendIy** [BetterDiscord/Installer#320]
The background images and effects (like color) for most themes suddenly stopped working recently. This happened after restarting discord. The other elements of the theme work, like text color and font, but specifically backgrounds aren't effected. This seems to be only the case for some themes though, as clearvision works. Also, if you include this line: 
@import url(https://clearvision.gitlab.io/v6/main.css);
at the beginning of any theme, that theme will become clearvision, regardless of what settings you have in its CSS.

**Comment by maenDisease** [comment]
This repo is only for issues with the Installer.

**Comment by ItMeSarah** [comment]
This repository is not for theme issues or general betterdiscord issues.
