### ISSUE TITLE
Replace setImmediate with window.focus({raise: true}) in devtools-opened event handler for better cross-platform compatibility

### ISSUE THREAD

**Issue by fled-dev** [BetterDiscord/Installer#321]
## Description
The current implementation of the devtools-opened event handler in main.js file of our Electron application uses setImmediate to bring focus back to the main window. However, this approach is not very efficient and may not work properly on some platforms.

To improve the cross-platform compatibility and performance of our application, we should replace setImmediate(() => { window.focus(); }); with window.focus({raise: true}); in the devtools-opened event handler.

This change will ensure that the main window is always brought to the foreground when the DevTools are opened, regardless of the platform. It will also eliminate the need for a callback function, making the code simpler and easier to understand.

## Proposed Solution
Replace setImmediate(() => { window.focus(); }); with window.focus({raise: true}); in the devtools-opened event handler in main.js file.

## Impact
This change will improve the cross-platform compatibility and performance of our Electron application. It should not have any adverse effects on the functionality or user experience of the application.

## References
[Electron documentation on window.focus()](https://www.electronjs.org/docs/api/browser-window#winfocusoptions)
[Electron documentation on setImmediate()](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args)

**Comment by Inve1951** [comment]
https://github.com/BetterDiscord/Installer/blob/fa31f1a177ee41067666470dba2f8d4aa8a8a33b/src/main/index.js#L49

**Comment by zerebos** [comment]
I feel like this explanation is insufficient. I see no mention of this in either of the docs you linked, and the option you mentioned doesn't even exist in the linked documentation.
