### ISSUE TITLE
"Downloading Asar File" With latest installer

### ISSUE THREAD

**Issue by LunaticWasTaken** [BetterDiscord/Installer#323]
**Describe the bug**
On the Latest installer appimage, trying to install it gets stuck on the "downloading asar file" message.

**To Reproduce**
1. Run AppImage file Either per rightclick -> Execute, or via `./Installer.AppImage`)
2. Selecting Stable version, and clicking install
3. Getting stuck.

**Expected behavior**
Installing without issues.

**Screenshots**
/

**System Information:**
 - OS: Arch Linux, kernel 6.2.1-arch1-1
- Discord Version: stable

**Additional context**
Running the version 1.1.2 (pre-latest) works perfectly fine.

**Comment by zerebos** [comment]
Duplicate of #226
