### ISSUE TITLE
[Feature] Wayland support.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BetterDiscord/Installer#327]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I use a 4K monitor, so I am forced to use Wayland because X does not scale correctly at high DPIs. I see no reason for this software to not support Wayland compositors, even if Discord itself is a different problem.

### Anything else?

https://github.com/BetterDiscord/BetterDiscord/issues/1528#issue-1575218969 depicts the current blurriness.

**Comment by QbDesu** [comment]
Are you running the app as a native wayland app using the proper electron parameters or settings? Have a look at the Arch Wiki's page on [Wayland](https://wiki.archlinux.org/title/Wayland#Electron) to see how to do this.

**Comment by RokeJulianLockhart** [comment]
@QbDesu, indeed http://forums.opensuse.org/t/164044 was the problem, but I still would like Wayland support. To that end, is this feasible for BetterDiscord, or should I merely follow https://support.discord.com/hc/en-us/community/posts/360047644231?

**Comment by QbDesu** [comment]
Simplest way is to modify the discord entry to start with the appropriate command line flags. The way to do this depends on the desktop environment you are using.

One way that may work in an environment like sway or Weston but probably wouldn't work in Plasma or Gnome is overriding the `.desktop` file by first copying the existing file from `/usr/share/applications/discord.desktop` (exact path varies depending on distribution) to the `~/.local/share/applications/` folder and adding ` --enable-features=WaylandWindowDecorations,UseOzonePlatform --ozone-platform=wayland` at the end of the `Exec=` line.

This shouldn't really be considered for BD to add as a feature. Wayland implementations are still unstable and the Wayland specification is still far from done. On top of that the Wayland support for Chromium - and therefore by extension Electron and Discord - is still experimental. Wayland is just not quite there yet.

**Comment by zerebos** [comment]
This sounds like an issue with the installer and not BD... moving issue

**Comment by zerebos** [comment]
As per the comment with @QbDesu this is not something we will be supporting ourselves. This will need to come from electron.
