### ISSUE TITLE
Instant crash with BD 1.2.1

### ISSUE THREAD

**Issue by BunCat09** [BetterDiscord/Installer#334]
**Describe the bug**
Discord crashes after saying "starting..." I think it happens when applying themes.

**To Reproduce**
1. Start Discord.
2. Wait for the main window (with the Discord facts) to pop up.
3. See the crash while themes are applied.

**Expected behavior**
Discord should open normally and I should see my beautiful theme and custom background.

**Screenshots**
https://imgur.com/a/qK9QuVZ

**System Information:**
 - OS: Windows 11 Pro
- Discord Version: Stable 1.0.9011

**Additional context**
Found the version number in the installation folder of Discord.
I use BD 1.2.1
I use the "SoftX" theme and I have ~20 plugins as well.

**Comment by maenDisease** [comment]
See https://github.com/BetterDiscord/BetterDiscord/commit/fbff8e2e52b8076cbab5e908ecdb2524665702e5, this commit should fix the crashing.
Either do a manual to apply or download the `betterdiscord.asar` from the commit artifact https://github.com/BetterDiscord/BetterDiscord/suites/11792215423/artifacts/615230861

And this repository is only for issues with the installer.

**Comment by BunCat09** [comment]
Thank you @maenDisease . the ".asar" file fixed the issue. I guess this will get fixed with an update so I am closing this.
