### ISSUE TITLE
Discord crash looping when installing

### ISSUE THREAD

**Issue by Shokaaaa** [BetterDiscord/Installer#335]
Whenever I run discord with BetterDiscord installed I just get into a crash loop. Repairing doesn't work either. It's also the discord just had an unexpected crash and that they'll report it. Uninstalled it and worked fine. Reinstalled started crashing again(I tried without plugins too) (nvm fixed it)

**Comment by DasBlackfur** [comment]
What did you do to fix it?

**Comment by SmartFridgeLG** [comment]
> Whenever I run discord with BetterDiscord installed I just get into a crash loop. Repairing doesn't work either. It's also the discord just had an unexpected crash and that they'll report it. Uninstalled it and worked fine. Reinstalled started crashing again(I tried without plugins too) (nvm fixed it)

same issue, how do you fix this? ive tried reinstalling to no avail.

**Comment by hexagon64** [comment]
![image](https://user-images.githubusercontent.com/126919322/227645146-ece4aaeb-69c9-414c-8c0a-5679dc26bf42.png)
Do these instructions to recover it if you are not lazy, and github certificate expired so anti-viruses will think the website that contains the installer is a malicious site.

**Comment by hexagon64** [comment]
if you are lazy
Here are some tips if you are lazy right now and still want to use betterdiscord without much problems.
Tip 1 **Use Cloudflare WARP** to use the BD Installer without any errors and **repair the client with the installer**
﻿
Tip 2 Some plugins still work, some don't, set `"addonErrors": false` in `settings.json`  in **C:\Users\YourName\AppData\Roaming\BetterDiscord\data\stable**
﻿
Tip 3 **Find the plugins** that causes the crashing loop so you can put them in a backup folder to put it back in later when the fix comes out.
﻿
**If you are not lazy and want to fix it now ask Disease for the "Crash Tracker" Thread redirection, as it has instructions in it for the manual fix.**

**Comment by notkirb** [comment]
> Tip 2 Some plugins still work, some don't, set `"addonErrors": false` in `settings.json` in **C:\Users\YourName\AppData\Roaming\BetterDiscord\data\stable** ﻿

this worked for me! thanks!

**Comment by notkirb** [comment]
my fix was this: https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

assuming that the newest version is causing issues, but the newest commit on github fixes this.

**Comment by randoomdude** [comment]
> ![image](https://user-images.githubusercontent.com/126919322/227645146-ece4aaeb-69c9-414c-8c0a-5679dc26bf42.png) Do these instructions to recover it if you are not lazy, and github certificate expired so anti-viruses will think the website that contains the installer is a malicious site.

Can you link the website so I can use the links, I'm also having trouble with browser discord phone verification so I'm trying to type it in manually each time and it's driving me crazy

**Comment by moghuu** [comment]
Here's the link from the image

Manual install + Video (3 minutes): https://canary.discord.com/channels/86004744966914048/1019725965284360283	
Alternative Method: https://cdn.discordapp.com/attachments/826217269323235358/1088979548575645706/betterdiscord.asar

You can find the post from the Official BD Discord

**Comment by notkirb** [comment]
new 1.9.1 update fixed this 👍
