### ISSUE TITLE
my discord keeps crashing and i dont know how to fix it even thou ive tried repairing my betterdiscord multiple times

### ISSUE THREAD

**Issue by IkariShinji01** [BetterDiscord/Installer#336]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by maenDisease** [comment]
This repository is only for issues with the BD installer,

**Comment by BOLSONARO22br** [comment]
Problemas com o plugin 
![image](https://user-images.githubusercontent.com/117112796/227690530-6295a8b1-bef3-495e-b0dd-85df35e9c59f.png)

**Comment by thechasingmaniwillchaseyou** [comment]
same happened to me

**Comment by NotAllowIce1102** [comment]
same issue

**Comment by 6Jack9** [comment]
i use mac and this happened to me
how to fix

**Comment by Aresoul** [comment]
Seems to be an issue with the plugins, I have deleted/removed the plugin files and better discord loads with no issues.

**Comment by Inve1951** [comment]
fixed in v1.9.1 release
