### ISSUE TITLE
still says discontinued version after downloading new version

### ISSUE THREAD

**Issue by VerstreuteSeele** [BetterDiscord/Installer#34]
After downloading the new launcher and installing it, discord still says its a discontinued version.
Tried uninstalling discord completely and deleting all folders as well

Am on Windows 10 newest updates etc. no other modifications to discord

**Comment by VerstreuteSeele** [comment]
fixed... your link in bandagedbd leads to be the old installer

**Comment by Tropix126** [comment]
If this is still relevant, it should be directed to the client's repo.
