### ISSUE TITLE
Installation of BD failes[Bug]

### ISSUE THREAD

**Issue by ItsdMeSoFYou** [BetterDiscord/Installer#340]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I tried reinstalling BD since I had some problems. 
When repairing or installing BD the installation failes and the installer shows the followinglog:

Starting Repair...

Creating required directories...
✅ Directory exists: C:\Users\Pasca\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\Pasca\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\Pasca\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\Pasca\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package from https://api.github.com/repos/BetterDiscord/BetterDiscord/releases/assets/100501170
❌ certificate has expired

The repair seems to have failed. If this problem is recurring, join our discord community for support. https://betterdiscord.app/invite

### Expected Behavior

Reinstalling of BD.

### Steps To Reproduce

1. Start the BD installer
2. Accept License agreement and press "Next"
3. Choose "Install" or "Repair"
4. Choose default Discord and press "Install" or "Repair"
5. Watch it fail installation

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.0

**Comment by StonedGoat** [comment]
having the same issue, seems like a security certificate or something on the website expired a few days ago???

**Comment by Risusama** [comment]
This is a problem on Github's side, not BetterDiscord. See how even our Github Avatars are broken?
Github's SSL/TLS certificate is expired.

I believe Github is aware of the problem, see https://www.githubstatus.com/

**Comment by KLalamex59** [comment]
Same issue here

**Comment by WiZiSergio** [comment]
same problem

**Comment by ItsdMeSoFYou** [comment]
Downloading the installer gives an SSL error. As @Risusama pointed out this seems to be an issue with a certificate tied to Github and not BD.

**Comment by ItsdMeSoFYou** [comment]
It seems to be fixed. Is it just for me, or for everyone else too?

**Comment by MrDuckz** [comment]
It does, for me too at least. Thanks

**Comment by MrDuckz** [comment]
But the reason why I tried to reinstall BD is because every time I try to open it with existing plugins, it just crashes

**Comment by StonedGoat** [comment]
> It seems to be fixed. Is it just for me, or for everyone else too?

download seems to be working for me as well now, i just reinstalled it.

anndd now discord is infinite crashing great :')
probably an issue on my end here but like haha wee troubleshooting

**Comment by ItsdMeSoFYou** [comment]
It's working again.
