### ISSUE TITLE
[Windows] BetterDiscord not running

### ISSUE THREAD

**Issue by NikNikovsky** [BetterDiscord/Installer#343]
**Describe the bug**
BetterDiscord does not load upon discord start.

**To Reproduce**
1. Install BetterDiscord (on Discord Canary)
2. Restart the computer/install a discord update (maybe)
**Expected behavior**
BetterDiscord loading with my plugins and themes

**Screenshots**
![obraz](https://user-images.githubusercontent.com/75254052/227782903-bd53f84b-96b3-4aee-944f-be8509742b96.png)
![obraz](https://user-images.githubusercontent.com/75254052/227782893-4ab4b072-1872-49c3-b3e0-0585ef582ee5.png)

**System Information:**
 - OS: Windows 11 22H2
- Discord Version: Canary 183858 (0519b2e)

**Additional context**
None.

**Comment by NikNikovsky** [comment]
and before you ask, yes I have the newest version of BetterDiscord

**Comment by ghost** [comment]
This repository is for the installer, not BD issues.   Join the support server and get help there
