### ISSUE TITLE
Yarn dev Error

### ISSUE THREAD

**Issue by naterfute** [BetterDiscord/Installer#344]
**Describe the bug**
I ran yarn dev and this happend 
![image](https://user-images.githubusercontent.com/106989409/227884284-8a42baee-dc64-4d9c-aabe-13303dfbc9c5.png)

**To Reproduce**
Follow the steps stated in the README.md file of this repository

**Expected behavior**
Unsure Because This is my first time using better discord

**Screenshots**
![image](https://user-images.githubusercontent.com/106989409/227884284-8a42baee-dc64-4d9c-aabe-13303dfbc9c5.png)

**System Information:**
 - OS: Linux Fedora 37
- Discord Version: Stable

**Additional context**

**Comment by zerebos** [comment]
Not sure why you're running in development mode instead of just running the binary if you want to use BD, but this has been fixed since https://github.com/BetterDiscord/Installer/pull/333 was merged
