### ISSUE TITLE
[Windows]

### ISSUE THREAD

**Issue by CorruptHomie** [BetterDiscord/Installer#345]
The installer refuses to install.

Here is the log:

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\doge6\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\doge6\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\doge6\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\doge6\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to get asset url from https://api.github.com/repos/BetterDiscord/BetterDiscord/releases
❌ connect ETIMEDOUT 140.82.113.6:443

The install seems to have failed. If this problem is recurring, join our discord community for support. https://betterdiscord.app/invite

**Comment by maenDisease** [comment]
Your network is blocking download. Here are some options:

A. Download a new installer from https://betterdiscord.app/
B. Restart/Shutdown pc, maybe twice
C. Disable proxy/vpn/antivirus/adblocker
D. Reinstall BD with a vpn enabled set to US
E. Do a manual installation https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

**Comment by Inve1951** [comment]
Like Disease said: it's a network issue. The installer can't solve it for you.
