### ISSUE TITLE
Right click crashes the client again

### ISSUE THREAD

**Issue by KLash17** [BetterDiscord/Installer#346]
So i wanted to unmute someone in a call, but it just crashes when I right click

**Comment by maenDisease** [comment]
This repository is only for issues with the BetterDiscord Installer.
For your specific issue, it's triggered by a plugin, wait for a BD update for it to be resolved.

**Comment by Technetium1** [comment]
Probably bettervolume plugin, this can be closed since it doesn't belong here.

**Comment by Inve1951** [comment]
wrong repo and not a BD issue
