### ISSUE TITLE
when i download it says virus detected, so whats that all about🤨

### ISSUE THREAD

**Issue by KAKTUSMAN21** [BetterDiscord/Installer#354]
what the title says, why does it say virus detected

**Comment by fowlis** [comment]
Can you elaborate? Where are you downloading the installer from? What does the message look like?

**Comment by KAKTUSMAN21** [comment]
I'm downloading for the github page but when I tried to it said "Failed to
download-virus detected"

**Comment by Technetium1** [comment]
@KAKTUSMAN21 Your browser is marking it, look for `...` or an arrow next to the download, and choose `keep`.

**Comment by zerebos** [comment]
We don't add viruses to our software.
