### ISSUE TITLE
error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by 999smokes** [BetterDiscord/Installer#368]
using the latest installer it keeps failing at downloading the asar file. is there any was to fix this?

Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\EarlyCollegeN2343\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\EarlyCollegeN2343\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\EarlyCollegeN2343\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\EarlyCollegeN2343\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package from the official website
❌ self signed certificate in certificate chain
Falling back to GitHub...
❌ Failed to get asset url from https://api.github.com/repos/BetterDiscord/BetterDiscord/releases
❌ self signed certificate in certificate chain

The install seems to have failed. If this problem is recurring, join our discord community for support. https://betterdiscord.app/invite

**Comment by 999smokes** [comment]
ive downloaded the installer from the better discord website and on github and neither work

**Comment by Inve1951** [comment]
This issue is likely on your end. Could be a misconfigured proxy or MITM-style software (firewall, packet sniffer, virus, etc).

**Comment by ghost** [comment]
As previous comment said, it's generally an issue on your end, your proxy, vpn, or antivirus is blocking the download on your end.

**Comment by 999smokes** [comment]
> As previous comment said, it's generally an issue on your end, your proxy, vpn, or antivirus is blocking the download on your end.

thanks ill try getting it figured out
