### ISSUE TITLE
BetterDiscord just not installing on the latest Discord Version

### ISSUE THREAD

**Issue by CyberBonk** [BetterDiscord/Installer#370]
**Describe the bug**
i just upgraded from the 32 bit to the new 64 bit discord version from the official site, after i installed it and reinstalled BetterDiscord i found that it is not working

**To Reproduce**
1)install the newest 64 bit discord version
2)retry to install BetterDiscord from the installer
3)open Discord app
4)Check options to make sure that the discord app isn't modified

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: windows 11
- Discord Version: Stable
- BetterDiscord Version: v1.3.0

**addational**
![image](https://github.com/BetterDiscord/Installer/assets/125883082/2569ba16-36c7-40e0-93bb-423785baaa51)

**Comment by Gabizin013** [comment]
Nada ainda

**Comment by CyberBonk** [comment]
> Nada ainda

?

**Comment by CyberBonk** [comment]
by the way, i figured BetterDiscord is not designed to run on x64, i reinstalled x32 and it installed fine, so this is more of an incompatibility than a bug

**Comment by zerebos** [comment]
> by the way, i figured BetterDiscord is not designed to run on x64, i reinstalled x32 and it installed fine, so this is more of an incompatibility than a bug

This is certainly not the case, it sounds like you just needed a clean install...

**Comment by CyberBonk** [comment]
> > by the way, i figured BetterDiscord is not designed to run on x64, i reinstalled x32 and it installed fine, so this is more of an incompatibility than a bug
> 
> This is certainly not the case, it sounds like you just needed a clean install...


right now yes, BetterDiscord Got updated to support x64 discord installations, this "issue" was posted right after discord changed teh default installer from x86 to x64 on their website, before the x64 version was labelled "Experimental"
