### ISSUE TITLE
BetterDiscord not installing into PTB nor Canary

### ISSUE THREAD

**Issue by Xiylah** [BetterDiscord/Installer#374]
**Describe the bug**
BetterDiscord not installing into PTB nor Canary

**To Reproduce**
1. Did a fresh uninstalled both PTB and Canary 
2. Installed PTB and Canary 
3. Tried to installed BetterDiscord on both
4. Says it installed but when opening it, it doesn't work

**Expected behavior**
Themes, Plugins and Betterdiscord being installed

**Screenshots**

**System Information:**
 - OS: Windows 10
- Discord Version: Latest PTB/Canary 

![DiscordCanary_5O7LRrnUHZ](https://github.com/BetterDiscord/Installer/assets/148124216/173931f4-d1bb-424f-a99b-238d34b38f28)

**Comment by fowlis** [comment]
Known. Discord pushed an update to both PTB & Canary that broke BetterDiscord and other client mods.

**Comment by Xiylah** [comment]
> Known. Discord pushed an update to both PTB & Canary that broke BetterDiscord and other client mods.

Yea I just saw it in the server. Thanks lol
