### ISSUE TITLE
After being prompted about having to reinstall better discord. I now got a new popup with a new beta installer. Installed it.. Installation said it went ok. But nothing changes.

### ISSUE THREAD

**Issue by SubsterNL** [BetterDiscord/Installer#38]
Same standard interface. The better discord settings options are there in the menu. When I choose a theme I previously created and activate it.. Nothing happens. This being on the latest updated windows 10 version of discord.

Nvm.. Apparently all previously created themes have to be redone as they are invalid

**Comment by Tropix126** [comment]
Issues regarding the client should be directed towards the respective repository.
