### ISSUE TITLE
Beta Installer doesnt load

### ISSUE THREAD

**Issue by klioxide-lol** [BetterDiscord/Installer#39]
Basically what happens, is I try installing BD Beta release installer, and the downloader gets stuck on "Attempting to kill Discord" | "Killing Discord"

![image](https://user-images.githubusercontent.com/80074052/113470594-5b7f5a00-941c-11eb-9fa0-e66583074765.png)

**Comment by rauenzi** [comment]
Appears to be a duplicate of #25

**Comment by rauenzi** [comment]
Make sure discord is fully closed using task manager before running the installer
