### ISSUE TITLE
didn't run

### ISSUE THREAD

**Issue by DFanso** [BetterDiscord/Installer#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by rauenzi** [comment]
This provided no information

**Comment by Tropix126** [comment]
Not enough information provided. Likely a duplicate of #36.

**Comment by kennyhjen** [comment]
Chưa hiểu
