### ISSUE TITLE
Crashes when using discord_arch_electron

### ISSUE THREAD

**Issue by ObserverOfTime** [BetterDiscord/Installer#41]
**Describe the bug**
At first, when installing BetterDiscord I get this error:
```
TypeError: process.electronBinding is not a function
```
Which can be fixed by changing both of its invocations to:
```js
(process.electronBinding ? process.electronBinding("command_line") : process._linkedBinding("electron_common_command_line"))
```
After that, BD simply crashes and disables itself but I can't find any crash logs.

**To Reproduce**
1. Install [discord_arch_electron](https://aur.archlinux.org/packages/discord_arch_electron/)
2. Install BetterDiscord on it
3. Fix the `process.electronBinding` issue
4. BD crashes when launching Discord

**Expected behavior**
Honestly, I didn't actually think it would work so this was expected…

**System Information:**
 - OS: Arch Linux
- Discord Version: 0.0.14
- Electron Version: 12.0.2

**Additional Context:**
* The location of the modules is the same as in regular Discord.
* The resources are moved from `./resources` to `/usr/lib/discord`.
* `app.asar` is unpacked into `/usr/lib/discord/app.asar.unpacked`.
* The system electron is used to run Discord through `app.asar`.
* `process.resourcesPath` points to `/usr/lib/electron/resources`.

**Comment by zerebos** [comment]
This sounds like an issue with BD itself and not the installer. Also given that `process.electronBinding` is not used in BD anymore I feel that this is stale. Please reopen with clarifications otherwise.

**Comment by ObserverOfTime** [comment]
BD v1.2.0 seems to work now on discord_arch_electron v0.0.15 with electron v13.1.4.
