### ISSUE TITLE
No plugin / theme options

### ISSUE THREAD

**Issue by AmAComputerNerd** [BetterDiscord/Installer#42]
**Describe the bug**
When BetterDiscord has installed, the plugins and themes tabs under the BetterDiscord category in settings don't appear.

**To Reproduce**
1. Run the windows installer on a PC that has installed BandagedBD.
2. Open the settings page in Discord once it has been installed.
3. See error.

**Expected behavior**
The plugins and themes tabs should appear under BetterDiscord like in the screenshot below.

**Screenshots**
First - what it was like pre-update (BandagedBD)
![Screenshot 2021-04-03 181122](https://user-images.githubusercontent.com/80492761/113471497-67186280-94a8-11eb-8344-cf0b05b53371.jpg)
Second - what it looks like post-update (Updated BetterDiscord)
![Screenshot 2021-04-03 181321](https://user-images.githubusercontent.com/80492761/113471500-6da6da00-94a8-11eb-92fb-5a5888f8ab85.jpg)

**System Information:**
 - OS: Windows 10 Home
- Discord Version: Stable 0.0.309

**Additional context**

**Comment by rauenzi** [comment]
This is a problem with BD not the installer
