### ISSUE TITLE
Not launching the EXE

### ISSUE THREAD

**Issue by theparaodxdoge** [BetterDiscord/Installer#43]
Not much to say. i attempt to open it and it doesn't execute.

https://user-images.githubusercontent.com/43124945/113474082-33e7bc00-9433-11eb-8c00-2b16bd2ba357.mp4

**Comment by TheRodrixHD** [comment]
same

**Comment by rauenzi** [comment]
Please check that your antivirus is not blocking it from running.

**Comment by rauenzi** [comment]
Duplicate of #36

**Comment by theparaodxdoge** [comment]
> Please check that your antivirus is not blocking it from running.

its not

**Comment by uber-ate** [comment]
anyone find a fix????
