### ISSUE TITLE
discord keep crashing on new version

### ISSUE THREAD

**Issue by lemi23** [BetterDiscord/Installer#44]
**Describe the bug**
As soon as I open discord after installing new release discord crash after 15-20 second and it doesn't matter if I do anything or no
![image_2021-04-03_175645](https://user-images.githubusercontent.com/81853193/113473681-00924500-94a6-11eb-86ab-d64c95a187a1.png)

(on the discounted version the bug doesn't happen)

**To Reproduce**
1. Go to 'https://drive.google.com/drive/folders/1dz6tNQzDs5RJnWgxIHXTBjqIu9eB_Wlj?usp=sharing' and download my plugins and theme
2. Use latest release of new launcher
3. create your own client id for autostartrichpresence plugin (deleted mine) and put it in the config file of plugin
4. open discord and watch it crash after 15-20seconds

**Expected behavior**
I expected the new release to not crash my discord because of my plugins or theme and I am willing to use discounted version if the issue isn't fixed

**System Information:**
 - OS: Windows 20H2 os build: 19042.867
- Discord Version: Stable 81329 (b80bbff)

**Additional context**
the discounted version where the issue doesn't persist: 'https://rauenzi.github.io/BetterDiscordApp/' windows exe if have been changed uploaded it here: https://drive.google.com/file/d/1reX9g0fKMjzU1tlb6_kBzUjREWxGSJum/view?usp=sharing

**Comment by arfanvlk** [comment]
mine also crashes the whole time

**Comment by arfanvlk** [comment]
> 1. Go to 'https://drive.google.com/drive/folders/1dz6tNQzDs5RJnWgxIHXTBjqIu9eB_Wlj?usp=sharing' and download my plugins and theme

try disabling autostartrichpresence that fixed it for me.

**Comment by dav1312** [comment]
This is a problem with AutoStartRichPresence, not with the installer

**Comment by rauenzi** [comment]
@lemi23 please remove all plugins from the folder then launch

**Comment by rauenzi** [comment]
Please reinstall. And keep in mind, issues with BD itself belong on that repo. This is for the installer.
