### ISSUE TITLE
Gift & GIF Buttons in Text Area Not Disappearing

### ISSUE THREAD

**Issue by TheSuperCasual** [BetterDiscord/Installer#49]
In short, the new feature to turn off the gift and gif buttons for the text box doesn't seem to work as expected.

I installed the newest update for BD this morning. Similarly, I had to deal with the same shenanigans yesterday where the update dialogue wouldn't go away after trying to install it. Today, at least, it worked, but the features that came with it did not. I just went to Settings and toggled the options on ASAP, but the buttons didn't disappear. I tried restarting Discord even, but the buttons remained.

 - OS: Windows
- Discord Version: Stable

I have only one other plugin on BD, which changes notification sounds.

**Comment by rauenzi** [comment]
This repository is for the installer. Not for BD itself.
