### ISSUE TITLE
Themes Won't Enable

### ISSUE THREAD

**Issue by jahcy** [BetterDiscord/Installer#51]
**Describe the bug**
When I try to turn my theme on, it doesn't turn on.

**To Reproduce**
1. Go to 'User Settings'
2. Click on 'Themes'
3. Scroll down to 'Theme'
4. Turn the theme on
5. See error

**Expected behavior**
The theme will not turn on

**Screenshots**
![bug](https://user-images.githubusercontent.com/81878911/113489500-9c19ba80-9492-11eb-974a-66077cff3103.JPG)

**System Information:**
 - OS: Windows
- Discord Version: Stable

**Additional context**
No additional context.

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/BetterDiscordApp/issues
