### ISSUE TITLE
New installer takes a long time to load

### ISSUE THREAD

**Issue by Riichie96** [BetterDiscord/Installer#53]
After I downloaded this new installer, every time that I start Discord the BD logo will consistently flash and say it's loading.

It takes mins for it to load all my themes and plugins (which aren't even a lot). 

I actually even did a completely fresh install with no themes and plugins and it still took a long time to load.

I also have automatic loading on and it still takes a long time.

Someone said to try disabling Emotes. I did that and it still takes a long time.

And for clarification, I'm not saying Discord is slow; Discord starts fine and loads fine. It's BD that takes a while to load. And specifically this new version of BD, because I have since reverted to an older version and I don't have this problem with it.

**System Information:**
 - **OS**: Windows 10 Home 20H2
- **Discord Version**: Stable

**Comment by rauenzi** [comment]
This sounds like an issue with BD and not with the installer, please open an issue over there.
