### ISSUE TITLE
Better discord not launching

### ISSUE THREAD

**Issue by ZEDERUS** [BetterDiscord/Installer#56]
After the update, better discord just stopped working altogether, I tried restarting my computer, re installing better discord, repairing better discord, and uninstalling and re installing but nothing has changed.

Discord is back to its old gray self after the update :( 

Better discord is just strait up gone for me right now

**Comment by iTzSharkSV** [comment]
Am having the same problem, i started up my pc today and there was an error, tried repairing and reinstalling but only deleting made it work and now am stuck with the old boring discord :>

**Comment by ZEDERUS** [comment]
I kinda fixed the problem with a big KINDA, i can make better discord
launch by opening one of those server folders, where you can group them
together but if I don't better discord will never launch.

give it a try, re: install better discord and try opening a group of
servers, you have a image below for reference if you did not understand
what I meant, see if that launches the better discord system.

Den mån 5 apr. 2021 kl 15:36 skrev SharkSV ***@***.***>:
