### ISSUE TITLE
Coloured text not working

### ISSUE THREAD

**Issue by Sh1ftyy** [BetterDiscord/Installer#57]
**Describe the bug**
Coloured text is not actually doing anything when I turn it on. I have restarted discord, reinstalled bd, and tried turning off all plugins, nothing works

**To Reproduce**
I turn on coloured text, nothing happens.

**Expected behavior**
The discord message text to be the same colour as the role of the person sending the message.

**System Information:**
 - OS: Windows
- Discord Version: Stable

**Comment by dav1312** [comment]
Thats an issue with BD, not with the installer.

**Comment by Tropix126** [comment]
Issues regarding the client should be opened on the respective repo. ==>Ahttps://github.com/rauenzi/BetterDiscordApp/
