### ISSUE TITLE
Arch Installer stuck on "Downloading asar file"

### ISSUE THREAD

**Issue by surprise** [BetterDiscord/Installer#58]
Steps to reproduce:
1. Download appimage installer
2. Mark it as executable (chmod +x)
3. Execute (./)
4. Select install and discord stable
5. Installation gets stuck on downloading asar file

**Comment by ObserverOfTime** [comment]
Do you have the same issue with the [AUR](https://aur.archlinux.org/packages/betterdiscord) version?

**Comment by surprise** [comment]
> Do you have the same issue with the [AUR](https://aur.archlinux.org/packages/betterdiscord) version?

Nope, that works completely fine.

**Comment by kennyhjen** [comment]
Kennyhjenhp1@gmail.com

**Comment by kennyhjen** [comment]
T

**Comment by kennyhjen** [comment]
> Steps to reproduce:
> 
> 1. Download appimage installer
> 
> 2. Mark it as executable (chmod +x)
> 
> 3. Execute (./)
> 
> 4. Select install and discord stable
> 
> 5. Installation gets stuck on downloading asar file

**Comment by Daddy2200** [comment]
@Yes

**Comment by ObserverOfTime** [comment]
Get these spammers out of here.

**Comment by mkono87** [comment]
Same issue here on linux mint.

**Comment by rauenzi** [comment]
Not exactly sure why it wouldn't work by itself but it would in the AUR aside from permissions issues.

**Comment by ObserverOfTime** [comment]
AppImages are weird. The AUR packages uses `yarn dist:dir` instead.

**Comment by StormAT** [comment]
I'm stuck on downloading asar file on windows 🤔

**Comment by ObserverOfTime** [comment]
Disable your antivirus and try again.

**Comment by StormAT** [comment]
> Disable your antivirus and try again.

sorry I didn't see this until now, I don't have any antivirus or VPN, so that was ruled out, and following the manual installation process rather than using the installer seemed to work, thanks anyway <3

**Comment by PH-man** [comment]
how to fix it?

**Comment by trasbr** [comment]
how

**Comment by nonetrix** [comment]
Same here on OpenSUS(OpenSUSE) also tried running as root no luck

**Comment by nonetrix** [comment]
I tried compiling it myself still no luck I have no idea also no useful output in JS console
