### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by Daddy2200** [BetterDiscord/Installer#61]
**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/81929259/113521438-74e0ed00-9567-11eb-9bf9-b6bc6702436e.gif)Steps to reproduce the behavior:
1. Go to ‘...’
2. Click on ‘....’
3. Scroll down to ‘....’

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by BlackYuzia** [comment]
best issue ever
