### ISSUE TITLE
keeps on saying "betterdiscord has temporarily disable itself. try removing all your plugins then restart discord" anyone know how to fix?

### ISSUE THREAD

**Issue by Sirpentious** [BetterDiscord/Installer#62]
i tried installing the new version but keeps on saying keeps on saying"betterdiscord has temporarily disable itself. try removing all your plugins then restart discord" i had deleted discord itself, i had deleted the old version and yet nothing worked, i even tried deleteding it on the new version and nothing had worked

**Comment by Curvn** [comment]
Have you tried removing your plugins/themes?

**Comment by rauenzi** [comment]
Please see the above.

**Comment by McStecca** [comment]
On Discord PTB removing themes and plugins doesn't work

**Comment by ItsOcto** [comment]
I had the same exact issue. What I did was delete the folder titled "betterdiscord" in my files which seemed to fix the problem.

**Comment by McStecca** [comment]
I removed message logger, uninstalled better discord, reinstalled and now it works

**Comment by dav1312** [comment]
Not really an issue with the installer itself

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to the appropriate repo => https://github.com/rauenzi/BetterDiscordApp/.
