### ISSUE TITLE
Unable to use plugins and themes on Discord Canary / PTB

### ISSUE THREAD

**Issue by Curvn** [BetterDiscord/Installer#63]
**Describe the bug**
Unsure if this is just a bug or not implemented or just isn't possible so thats why i labeled it as a bug.

**To Reproduce**
1. Go to 'Discord Canary / PTB'
2. Click on 'User Settings'
3. Scroll down to 'BetterDiscord'
4. Not seeing Emotes, Custom CSS, Plugins, Themes

**Expected behavior**
Seeing Emotes, Custom CSS, Plugins, Themes. Being able to disable/enable them the say exact way I'm able too on Discord.

**Screenshots**
https://gyazo.com/5d280ca4e1b7b2bf65eef6506d899fae

**System Information:**
 - OS: Windows
- Discord Version: Canary 81364 (fece00e)

**Additional context**
None.

**Comment by rauenzi** [comment]
Please file issues with the client in the correct repo
