### ISSUE TITLE
The installer will not allow the selection of the discord folder on PCLinuxOS with KDE

### ISSUE THREAD

**Issue by RealDoigt** [BetterDiscord/Installer#64]
**Describe the bug**
Discord is greyed out and thus cannot be selected by the installer. So the installer will never be able to find Discord.

**To Reproduce**
1. Have PCLinuxOS with KDE on your computer.
2. Download the appimage from the releases.
3. Run the installer appimage.
4. Click "Install BetterDiscord"
5. Click "Next"
6. Click "Discord"
7. Click "Browse"
8. Go to the installation folder in "usr/share/discord/"

**Expected behavior**
I expected to be able to select the discord executable file so that I can proceed with the installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/57451013/113538361-07ee4700-95a9-11eb-9f56-c8843885be3b.png)

**System Information:**
 - OS: PCLinuxOS
- Discord Version: [default] [BUILD INFO] Release Channel: stable, Build Number: 81329, Version Hash: b80bbff00049d94903b5a20f5ad1d77df37266f1**

**Comment by rauenzi** [comment]
Did the installer not auto-detect the correct location? Also you should browse to a path, not an executable. On Linux it will be something like `~/.config/discord`

**Comment by RealDoigt** [comment]
Oh that could be made clearer, though I've tried both config and installation folders but it didn't work, so I assumed it wanted an executable.

**Comment by Tropix126** [comment]
Try injecting the_ `resources` folder.

**Comment by RealDoigt** [comment]
> 
> 
> Try injecting the `resources` folder.

Didn't work :-(

**Comment by rauenzi** [comment]
On linux it does not want the `resources` directory. It ideally wants `~/.config/discord/<version>/modules/discord_desktop_core` where `<version>` is your version number

**Comment by RealDoigt** [comment]
it worked!
