### ISSUE TITLE
The new installer doesn't work 

### ISSUE THREAD

**Issue by Kkeev** [BetterDiscord/Installer#65]
The new installer won't let me click on install because it's greyed out.

**Comment by dav1312** [comment]
You probably didn't select the Discord version you wanted BD to be installed in

![SelectDiscordVersion](https://user-images.githubusercontent.com/63931154/113610026-e181e780-964c-11eb-906f-d2dc1fe1ee94.gif)

**Comment by Kkeev** [comment]
I'm stupid, I thought it auto-selected. Thanks for the help.
