### ISSUE TITLE
New Better Discord crashes

### ISSUE THREAD

**Issue by urioTV** [BetterDiscord/Installer#66]
I get pop-up with info that bd crashed discord and running vanilla. Old better discord still working without an issue.

**Comment by Floatingamer** [comment]
yes i have had the same issue its to do with the amount of plugins or the plugins you have it needs to be fixed but a quick fix is if you cant even get into bd put all your plugins in a folder and drag them individually to find the issue one or just dont use any heavy plugins

**Comment by dav1312** [comment]
This is not an issue with the installer but with BD itself

**Comment by urioTV** [comment]
First, I tried without plugins and still crashes. Second, then give option to install old version of BD in this installer because the only way to have working BD is using old installer.

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to the appropriate repo => https://github.com/rauenzi/BetterDiscordApp/.
