### ISSUE TITLE
Add an andorid betterdiscord

### ISSUE THREAD

**Issue by Wumpus-Github** [BetterDiscord/Installer#67]
If there is an android version, where is it?

**Comment by dav1312** [comment]
Don't open an issue in the installer repo for this

**Comment by Daddy2200** [comment]
>Yes install installed for this iOS

**Comment by Tropix126** [comment]
The android version of discord is written in an entirely different language and would need it's own theme/plugin ecosystem, as well as a huge time investment development-wise. This is simply out of scope, as the BD development team is rather small and this would be an entirely different project.
