### ISSUE TITLE
>Yes install installed for this iOS

### ISSUE THREAD

**Issue by Daddy2200** [BetterDiscord/Installer#68]
>Yes install installed for this iOS 

__Originally posted by @Daddy2200 in https://github.com/BetterDiscord/Installer/issues/67#issuecomment-813598653__

**Comment by Daddy2200** [comment]
> >Yes install installed for this iOS 
> 
> 
> __Originally posted by @Daddy2200 in https://github.com/BetterDiscord/Installer/issues/67#issuecomment-813598653__

{Never delete}

**Comment by Tropix126** [comment]
See my comment in #67.
