### ISSUE TITLE
Newest Version Causes My Theme To Be Dark

### ISSUE THREAD

**Issue by Grip555** [BetterDiscord/Installer#72]
Using any ClearVision theme makes it a lot darker than on the previous version of BD.

What it's meant to look like:
https://clearvision.gitlab.io/images/amber.jpg

What it actually looks like:
https://imgur.com/XmE3hO2

**Comment by Tropix126** [comment]
This is not related to the installer or likely BD itself. You should probably reopen this issue on the ClearVision repository.

**Comment by Grip555** [comment]
I did speak to ClearVision and they said it wasn't their fault and I should speak to BD instead.
