### ISSUE TITLE
BetterDiscord removed after Discord update

### ISSUE THREAD

**Issue by MelodyZ02** [BetterDiscord/Installer#76]
As the title suggests my betterdiscord was removed when I updated my discord, and I can't reinstall it somehow. Not only this but earlier installers aren't working either. Does anybody have the same problem?

**Comment by AutoKill** [comment]
> As the title suggests my betterdiscord was removed when I updated my discord, and I can't reinstall it somehow. Not only this but earlier installers aren't working either. Does anybody have the same problem?

yeah my betterdiscord was also removed after update.

**Comment by L0c4lh0sT-Zero** [comment]
Same for me, It shows the settings for betterdiscord but not the themes, custom css, plugins, emojis, etc.. (Check image for reference) Reinstalling doesn't solve it, neither does repairing. 
![image](https://user-images.githubusercontent.com/44318059/113726461-8c99ac00-96f4-11eb-988c-c5fee8bca3f9.png)

**Comment by anxiouslytherin** [comment]
Well fuck. Same here

**Comment by xZinio** [comment]
Weird, same happend to me already a couple of times but reinstalling fixed just as it always did.

**Comment by BruhNye** [comment]
same here [on linux]. i reinstalled it multiple times but it remains broken

**Comment by Tropix126** [comment]
> Same for me, It shows the settings for betterdiscord but not the themes, custom css, plugins, emojis, etc.. (Check image for reference) Reinstalling doesn't solve it, neither does repairing.
> ![image](https://user-images.githubusercontent.com/44318059/113726461-8c99ac00-96f4-11eb-988c-c5fee8bca3f9.png)

This will be fixed in a later update to the client.

**Comment by Tropix126** [comment]
> As the title suggests my betterdiscord was removed when I updated my discord, and I can't reinstall it somehow. Not only this but earlier installers aren't working either. Does anybody have the same problem?

Try going to `%localappdata%/Discord` and deleting `app-0.0.309`, then reinstalling BetterDiscord.

**Comment by RealCountrx** [comment]
All I had to do was re run the BetterDiscord Downloader

**Comment by BruhNye** [comment]
> Try going to `%localappdata%/Discord` and deleting `app-0.0.309`, then reinstalling BetterDiscord.
any fix for linux?

**Comment by rauenzi** [comment]
For those still having issues locate your BetterDiscord folder, rename it, then rerun the BD installer.

**Comment by UltraHQ** [comment]
I tried every fix listed here and none of them worked. Any other fix I could try?

**Comment by SylveonBottle** [comment]
Just installed BetterDiscord, nothing showed up. It was as if the installer failed to install.

Deleted %appdata%\BetterDiscord did nothing.
Running the installer a second time did nothing.
Running the installer's Repair (then installing) shows this:
![image](https://user-images.githubusercontent.com/17802843/114311385-62087400-9aa3-11eb-9f54-e554ec33fb23.png)

It seems like Discord just made an update to get rid of BetterDiscord.

**Comment by importly** [comment]
Using the BetterDiscord installer and repairing it worked for me.

**Comment by AVKatoch** [comment]
still doesnt work for me and I use windows and none of these work

**Comment by Koko37yt** [comment]
Tried whatever fixes are suggested here still i don't have the themes /plugins tabs, only BetterDiscord tab is here :c
