### ISSUE TITLE
Discord on boot loop

### ISSUE THREAD

**Issue by HTDMPRO** [BetterDiscord/Installer#77]
It's not exacly "boot loop", its more like an "update loop", it just does update 1 of 1, than for 0,1s searches for another one, than updates 1 of 1 and the circle continues...

There's the video:
https://user-images.githubusercontent.com/62035578/113762677-21ae9c00-9719-11eb-95f8-e6446c7d63d2.mp4

Edit: sorry for the music in the background

**Comment by Tropix126** [comment]
Have you tried running the repair option?

**Comment by HTDMPRO** [comment]
Yeah, nothing changed, reinstalled discord with deleting everything on appdata folder fixed it, I guess something broke discord first time around but it was okay the second time.

**Comment by Tropix126** [comment]
Issue closed unless anything else comes up.
