### ISSUE TITLE
Crashing whenever I try to watch a friend streaming

### ISSUE THREAD

**Issue by FeralFae** [BetterDiscord/Installer#79]
It closes out the app and cuts me from call, I relaunch and it says that Better Discord caused a crash and to try repairing and disabling plugins. I did all this, it still crashes.

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/betterdiscordapp.

Also:
![image](https://user-images.githubusercontent.com/42101043/113920861-f4aac980-97aa-11eb-966f-9e1f4a336472.png)
