### ISSUE TITLE
Moving from Bandaged BetterDiscord to BetterDiscord Drops Emotes

### ISSUE THREAD

**Issue by Link5261** [BetterDiscord/Installer#80]
**Describe the bug**
Global Twitch emotes like Kappa, PogChamp, and FrankerZ (among many others) are no longer showing in emote form, and instead show as vanilla behavior text.

**To Reproduce**
1. Use the updated BetterDiscord installer.
2. Install to Stable.
3. In any chat, type Kappa or another Twitch emote.
4. See that text remains text, and does not replace with the emote.

**Expected behavior**
As was the behavior in Bandaged BetterDiscord, the text (case-sensitive) would be replaced automatically with the corresponding emote, only for the viewer with (Bandaged) BetterDiscod installed.

**Screenshots**
When updated BetterDiscord is installed:
 ![Kappa_not_working_BetterDiscord](https://user-images.githubusercontent.com/43685379/113926014-af41c880-97b9-11eb-90c2-5a855e47d79e.png)
When "unsupported" Bandaged BetterDiscord is installed:
 ![Kappa_working_Bandaged_BetterDiscord](https://user-images.githubusercontent.com/43685379/113926015-af41c880-97b9-11eb-9985-0ef355089a38.png)

**System Information:**
 - OS: Windows 7 64-bit
- Discord Version: Stable

**Comment by dav1312** [comment]
Issues regarding the client should be directed to the appropriate repo => https://github.com/rauenzi/BetterDiscordApp/
