### ISSUE TITLE
Betterdiscord seems to have crashed your discord client

### ISSUE THREAD

**Issue by Pishgrumpy** [BetterDiscord/Installer#81]
at random times betterdiscord crashes and for some reason this only happened since the 29 day old patch. is this common for anyone else?
![image](https://user-images.githubusercontent.com/81574381/114188970-f6f75a00-9949-11eb-92da-12c3f7f5c2c7.png)

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/betterdiscordapp
