### ISSUE TITLE
BetterDiscord Beta deleting Discord

### ISSUE THREAD

**Issue by 3aun** [BetterDiscord/Installer#83]
I tried to install BetterDiscord Beta but it completely deleted the discords Update.exe file.

I expected BetterDiscord Beta to install properly but as there are with many Beta's it can happen most of the Time that there are Bugs.

https://prnt.sc/118fgaa

 - OS: [Windows 10]
- Discord Version: [newest stable].

**Comment by Tropix126** [comment]
Try reinstalling discord.
