### ISSUE TITLE
BetterDiscord is in conflict

### ISSUE THREAD

**Issue by dfdddfd** [BetterDiscord/Installer#84]
**Describe the bug**
BetterDiscord is in conflict

**To Reproduce**
1. BetterDiscord Install
2. Discord Restart
3. See Error

**Expected behavior**
Betterdiscord is need to operate normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/60836631/114255300-81de6000-99ef-11eb-854e-d227af1fcca1.png)

**System Information:**
 - OS: Windows 10
- Discord Version: PTB
- 
**Additional context**

**Comment by dav1312** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/betterdiscordapp

**Comment by Tropix126** [comment]
^^
