### ISSUE TITLE
New version Feels sluggish 

### ISSUE THREAD

**Issue by TRaSH-** [BetterDiscord/Installer#85]
**Describe the bug**
New version Feels sluggish 

**To Reproduce**
just use it for a while and you notice it get's sluggish 

**Expected behavior**
the old bandageBD was as snappy as without using a add-on, so i expect a new version doesn't impact the performance

**Screenshots**
Sorry can't make screenshots of slowness 

**System Information:**
 - OS: Windows 10
- Discord Version: Stable

**Additional context**
The old version BandageBD installer doesn't work anymore, the new one does but after some while of usage it's getting to slow, when typing and you want to remove a few words you have a big delay, when you paste a screenshot or something on a server its just slow

**Comment by dav1312** [comment]
Issues regarding the client should be directed to => https://github.com/rauenzi/betterdiscordapp

**Comment by Tropix126** [comment]
See above message.
