### ISSUE TITLE
Plugins and themes not working

### ISSUE THREAD

**Issue by ArdynBlake** [BetterDiscord/Installer#86]
![image](https://user-images.githubusercontent.com/82282299/114278584-6ba0c600-9a28-11eb-9c45-61dd0480b3ca.png)
Where all the other tabs used to be under BetterDiscord settings, there is now just settings with no way to access my plugins or themes folders. My plugins and themes also do not work within this update.

**Comment by Tropix126** [comment]
Issues regarding the client should be directed to http://github.com/rauenzi/betterdiscordapp/

**Comment by ArdynBlake** [comment]
Why should it be when this issue only comes from your installer, your client?
