### ISSUE TITLE
Ability to install to Discord Development Build

### ISSUE THREAD

**Issue by dikahdoff** [BetterDiscord/Installer#87]
Windows: https://discord.com/api/download/development?platform=win
Debian: https://discord.com/api/download/development?platform=linux
macOS: https://discord.com/api/download/development?platform=osx

Discord keeps a secret development build, the client says it's Canary, but it gets even more updates and uses less resources. When I select this version in the installer, the installer just says that Discord Canary is not installed.

**Comment by Tropix126** [comment]
This has generally been known, however it's extremely low priority for a few reasons.
- Discord development is actually an abandoned client. The client in practice just redirects to the canary API endpoint.
- Barely anyone uses it and it's generally not well known.
- There will need to be some changes in the client for it to work.

There is currently an [open pull ](https://github.com/rauenzi/BetterDiscordApp/pull/526)to add support on the client, however if this pull does get merged it will likely __not__ be added to the installer. Instead you'll most likely have to perform a manual injection by building the client from it's source code and running the `inject` script. This is for the reasons listed above.

**Comment by Tropix126** [comment]
Leaving this issue open for discussion.

**Comment by dikahdoff** [comment]
Created a fork: https://github.com/dikahdoff/BetterDiscordApp
Use `npm run inject dev` to install to Dev build.

**Comment by zerebos** [comment]
I still don't understand the point of supporting it, I cannot seem to get any definitive information about the utility of the development build. https://github.com/rauenzi/BetterDiscordApp/issues/520#issuecomment-812629675

**Comment by ghost** [comment]
> I still don't understand the point of supporting it, I cannot seem to get any definitive information about the utility of the development build. [rauenzi/BetterDiscordApp#520 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/520#issuecomment-812629675)

i mean its basicly a fork of canary but with a few differences. i still think it should be install able just incase the client changes build branch to its own thing or if someone just likes the black icon

**Comment by Annabxlla** [comment]
> 
> 
> I still don't understand the point of supporting it, I cannot seem to get any definitive information about the utility of the development build. [rauenzi/BetterDiscordApp#520 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/520#issuecomment-812629675)

You can add the feature for manually injecting via nodejs directly and just not add it to the UI installer. It's almost the same as Canary but has a few minor changes. It's fairly simple to do, (like 6 people have git cloned and modified it already to allow for it) There is already a PR (a few) for it if you want to just add the: `npm run inject dev` feature.


>     * Discord development is actually an abandoned client. The client in practice just redirects to the canary API endpoint.
> 
>     * Barely anyone uses it and it's generally not well known.
> 
>     * There will need to be some changes in the client for it to work.

It's not abandoned, there is some sort of automated system in place with it where the staged updates to Canary are pushed to clients right away to the Dev build. I have 3 systems with the Dev build and Canary build and the Dev builds get updates a few days before Canary. It's not well known because discord doesn't tell people you can get it, in return barely anyone uses it (although in recent days more people seem to be using it now.) The Dev build is running BBD perfectly fine for me, well besides for rauenzi/BetterDiscordApp#821 that is. And the only change for the Dev build to have BBD injected was to change like three of four lines.

**Comment by zerebos** [comment]
I don't plan to add this to the installer

**Comment by tokenlogging** [comment]
Is it running the latest version of discord? Or does it update slower or not at all.

**Comment by pawpaw5** [comment]
not working

**Comment by ghost** [comment]
did they stop supporting it? I get this if i open the installer
![Knipsel](https://user-images.githubusercontent.com/89196093/209870789-afacfb7f-2f16-48b8-869a-b57bd4db99d8.PNG)

**Comment by BurAndBY** [comment]
> did they stop supporting it? I get this if i open the installer ![Knipsel](https://user-images.githubusercontent.com/89196093/209870789-afacfb7f-2f16-48b8-869a-b57bd4db99d8.PNG)

you are probably out of space or your internet sucks

**Comment by Noxillio** [comment]
> > did they stop supporting it? I get this if i open the installer ![Knipsel](https://user-images.githubusercontent.com/89196093/209870789-afacfb7f-2f16-48b8-869a-b57bd4db99d8.PNG)
> 
> you are probably out of space or your internet sucks

Not what this means.

The Development client no longer installs properly. If you have an existing install it will continue to work. Any hope for using the Development client again on a new install relies on an update causing the client to start working... again.

**Comment by SPLATPLAYS** [comment]
> > > did they stop supporting it? I get this if i open the installer ![Knipsel](https://user-images.githubusercontent.com/89196093/209870789-afacfb7f-2f16-48b8-869a-b57bd4db99d8.PNG)
> > 
> > 
> > you are probably out of space or your internet sucks
> 
> Not what this means.
> 
> The Development client no longer installs properly. If you have an existing install it will continue to work. Any hope for using the Development client again on a new install relies on an update causing the client to start working... again.

do you think they will ever actually update it again?

**Comment by wockaid** [comment]
if u delete update in the folder and run it it works perfectly fine

**Comment by revellntp** [comment]
@wockaid which folder does it exclude?

**Comment by Noxillio** [comment]
> if u delete update in the folder and run it it works perfectly fine

Wow, it actually does. That's pretty cool.

**Comment by Noxillio** [comment]
> @wockaid which folder does it exclude?

Delete `Update.exe` from `%localappdata%\DiscordDevelopment`

**Comment by josea0511** [comment]
I've used the Development client of Discord by using the WSL with a command, but I forgot it... I'm pretty sure it still works.
