### ISSUE TITLE
Can't Install Themes

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [BetterDiscord/Installer#88]
**Describe the bug**
Can't Install Themes to Better Discord

**To Reproduce**
1. Install BetterDiscord Beta.
2. Go to User settings
3. Thier is no themes tab
4. can't install themes

**Expected behavior**
I want to install Themes

**Screenshots**
![image](https://user-images.githubusercontent.com/79018578/114314360-495e8500-9ac8-11eb-8ec1-030674d27b22.png)
![image](https://user-images.githubusercontent.com/79018578/114314366-51b6c000-9ac8-11eb-968b-f82436896cb8.png)

**System Information:**
 - OS: Windows 10 Pro
- Discord Version: Latest

**Comment by rauenzi** [comment]
This is actually an issue with the client and not the installer. Can you please tell me what the most recent logs in console show for BD?

**Comment by thomaschocho** [comment]
I don't know where are those logs, so I can't show you. But I had the same problem as him and I moved my main account from the normal discord version and logged it in on PTB because the plugins work there, and the second account on the normal version. So logging out and back in somehow fixed it and now plugins work on the normal one too, I'm not sure if that's what fixed it though.

**Comment by Pixelplayz2215YT** [comment]
How do I get logs?

**Comment by maxiruf** [comment]
Hello, i had the same problem just now. All you need to do to fix the bug is:
1. Open the BD Installer
2. Select Repair 

Thats it. It will ask u if u want to install BD again and boom finished

Pls let me know if it works for you

**Comment by maxiruf** [comment]
> How do I get logs?

Look at my comment i found a way to fix the bug

**Comment by maxiruf** [comment]
> I don't know where are those logs, so I can't show you. But I had the same problem as him and I moved my main account from the normal discord version and logged it in on PTB because the plugins work there, and the second account on the normal version. So logging out and back in somehow fixed it and now plugins work on the normal one too, I'm not sure if that's what fixed it though.

Look at my comment i found a way to fix the bug

**Comment by maxiruf** [comment]
> This is actually an issue with the client and not the installer. Can you please tell me what the most recent logs in console show for BD?

Look at my comment i found a way to fix the bug

**Comment by Pixelplayz2215YT** [comment]
> Hello, i had the same problem just now. All you need to do to fix the bug is:
> 
> 1. Open the BD Installer
> 
> 2. Select Repair 
> 
> 
> 
> Thats it. It will ask u if u want to install BD again and boom finished
> 
> 
> 
> Pls let me know if it works for you

Thanks, I'll let you know

**Comment by thomaschocho** [comment]
> > I don't know where are those logs, so I can't show you. But I had the same problem as him and I moved my main account from the normal discord version and logged it in on PTB because the plugins work there, and the second account on the normal version. So logging out and back in somehow fixed it and now plugins work on the normal one too, I'm not sure if that's what fixed it though.
> 
> Look at my comment i found a way to fix the bug

No, I tried doing that first and didn't work. But mine works now so can't try.
