### ISSUE TITLE
Crash error after installing BD

### ISSUE THREAD

**Issue by Kheath812** [BetterDiscord/Installer#89]
**Describe the bug**
After using the new installer to install BD, clicking discord to open it gives a huge error. Ive tried uninstalling BD and Reinstalling and repairing.

**Screenshots**
https://i.imgur.com/f7xYuFQ.png

**System Information:**
 - OS: Win 10
- Discord Version: Stable

**Comment by rauenzi** [comment]
This is actually an issue with the client and not the installer. Please rename the BetterDiscord directory (`%appdata%\BetterDiscord`) and reinstall. If the issue persists, open an issue over at https://github.com/rauenzi/BetterDiscordApp
