### ISSUE TITLE
better discord shuts down discord by showing up an error

### ISSUE THREAD

**Issue by MisterDefender** [BetterDiscord/Installer#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by dav1312** [comment]
You didn't provide any information at all and thats not an installer issue

**Comment by MisterDefender** [comment]
I appreciate u for replying me so quick...thankyou!!

**error:**
![Screenshot (136)](https://user-images.githubusercontent.com/65152380/114413273-76e02700-9bcb-11eb-978e-08c6085ba825.png)

**---->>>>>** my discord didn't have any plugin installed.

**Comment by MisterDefender** [comment]
specs:
Windows 10 64 bit
intel i5 8th gen
16gb ram

**Comment by bl4st-github** [comment]
yeah i have the same problem as @MisterDefender and even when i take out all plugins same thing happens. Strange thing is though is that i have discord PTB as well as Discord Stable and only Discord Stable isnt working with this new BetterDiscord Launcher

**Comment by rauenzi** [comment]
This is a client issue (https://github.com/rauenzi/BetterDiscordApp), not an installer issue.
