### ISSUE TITLE
Colored Text Option Not Working

### ISSUE THREAD

**Issue by dphantasm** [BetterDiscord/Installer#91]
Toggled the "Colored Text" option on as usual after updating, but it doesn't seem to work anymore. Tried both with and without a theme, and with and without plugins installed. Also attempted to repair the BD installation and check again, but no dice. 

This is on current Stable Discord, Windows 10.

**Comment by dav1312** [comment]
1) This is a known issue
2) Issues regarding the client should be directed to the appropriate repo => https://github.com/rauenzi/BetterDiscordApp/
