### ISSUE TITLE
Doesn't work with last Discord update (1.0.9001)

### ISSUE THREAD

**Issue by barbaduk** [BetterDiscord/Installer#92]
BD is in infinity loading state.
I completely deleted Discord and BD with all folders in appdata.
Then i installed discord, restarted it couple of times so it would update to 1.0.9001 and then installed last BD release (zero themes or plugins, 100% default).
And yeah, i tried disabling Emotes and everything else and restarting and waiting.
It just doesn't work and doesn't load plugins (of course) if i add them.

![BDdw](https://user-images.githubusercontent.com/41954202/114463163-bf5c0c80-9bec-11eb-817b-0d7dbd5f8686.jpg)

**Comment by AdriGeeK03** [comment]
Yeah same, I don't have any option that I checked in the settings added :/

**Comment by Koko37yt** [comment]
Having the same issue since approximately 1 week and found no issue :c

**Comment by Koko37yt** [comment]
Update* Waited like 1hour without doing anything on discord and it somehow loaded

**Comment by rauenzi** [comment]
This is a client issue (https://github.com/rauenzi/BetterDiscordApp), not an installer issue.
