### ISSUE TITLE
BetterDiscord not working.

### ISSUE THREAD

**Issue by twdaggar** [BetterDiscord/Installer#93]
Hi. My BetterDiscord isn't starting with discord. 

- I am using the Beta Launcher

- I repaired

- I use Windows 

- I installed for stable

 There's **no** flashing B icon everytime I start up discord. Please help!
 
 
![image](https://user-images.githubusercontent.com/82417046/114465376-51611680-9be7-11eb-95eb-f9003af4255e.png)

**Comment by twdaggar** [comment]
Update: There's no bdsettings.json. Huh? I did not delete it.

**Comment by dav1312** [comment]
Make sure that you are installing BD in the appropriate app folder
By this I mean, that your host could be 1.0.9001 (this appears under the log out tab in the settings) and you could be installing BD in app-0.0.309

**Comment by rauenzi** [comment]
Please show installer log and versions.

**Comment by Thee-GOLDEN-GRIFFIN** [comment]
same is happening to me also does discord need to be 64 bit?

**Comment by Thee-GOLDEN-GRIFFIN** [comment]
dav1312 commented 3 days ago
Make sure that you are installing BD in the appropriate app folder
By this I mean, that your host could be 1.0.9001 (this appears under the log out tab in the settings) and you could be installing BD in app-0.0.309 

btw mine says  app-0.0.308

**Comment by klioxide-lol** [comment]
Im having this issue too. Im on most recent discord version, just uninstalled and reinstalled both discord and BetterDiscord.
