### ISSUE TITLE
BetterDiscord crashing on launch

### ISSUE THREAD

**Issue by mickeygeecom** [BetterDiscord/Installer#95]
**Describe the bug**

**To Reproduce**
1. Install lastest production Discord
2. Install/Repair to lastest BetterDiscord
3. (Also tried deleting everything and starting over, including theme and plugins, no juice)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5321009/114521594-ddecf280-9c42-11eb-93c1-ebf8d66f9b64.png)

**System Information:**
 - OS: Win10 x64
- Discord Version: Stable

**Additional context**

**Comment by bl4st-github** [comment]
Same problem for me, verified it only happens for Stable and not my BD installation for discord PTB

**Comment by YahBoiiJose** [comment]
I'm having the same issue on stable and PTB. The only thing that's different is that i'm on Linux Mint 20.1.

**Comment by betawil** [comment]
Same here, i tried to reinstall both discord and BD, delete the the BD folder on appdata and reinstall and still crashing the discord when i try to enter in any discord call.

**Comment by bl4st-github** [comment]
another person with the same issue:

[https://github.com/BetterDiscord/Installer/issues/90](url)

**Comment by rauenzi** [comment]
This is a client issue (https://github.com/rauenzi/BetterDiscordApp), not an installer issue.
