### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ThatGuyJamal** [BetterDiscord/Installer#98]
When trying to click betterdiscord.net, it says it can't be found?

I know [this](https://betterdiscordlibrary.com/) link works but why is this site down?

**Comment by dav1312** [comment]
`1.` That is not an official BetterDiscord website. Don't open issues about it in any BetterDiscord repository
`2.` This is **not** an issue with the installer

**Comment by Arias122** [comment]
can you give me a link to a oficial website of better discord?


czw., 15 kwi 2021 o 11:47 dav1312 ***@***.***> napisał(a):
