### ISSUE TITLE
Editor moves the cursor when used with custom fonts

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [BetterDiscord/Installer#99]
**Describe the bug**
The CSS Editor moves the cursor forward, yet it still edits before the cursor if the font is different

**To Reproduce**
Settings -> Custom CSS ->
```
* {
    font-family: 'Comic Sans MS' !important;
}
```
And propably turn on liveupdate

**Expected behavior**
For the cursor not to be displaced

**Screenshots**
*I didn't move the cursor: I just clicked backspace for the screenshots*
![obraz](https://user-images.githubusercontent.com/58668179/114664275-c291ee00-9cfb-11eb-9871-34e15f2d6e42.png)
![obraz](https://user-images.githubusercontent.com/58668179/114664296-caea2900-9cfb-11eb-96d3-6493aa76e49b.png)

**System Information:**
 - OS: Windows 10
- Discord Version: Stable
- BetterDiscord Version: Latest from releases (beta), but it was present before this version

**Comment by dav1312** [comment]
`1.` Don't use the universal selector to change your font, ask for help in the [#custom-css](https://discord.gg/0Tmfo5ZbORCRqbAd
) channel to know how to properly do it
`2.` This is **not** an issue with the installer

**Comment by rauenzi** [comment]
Please see above. In the end this would be an issue with the Monaco editor, not BD itself.
